apiVersion: skycloak.m.crossplane.io/v1alpha1
kind: CaptchaDomain
metadata:
  annotations:
    meta.upbound.io/example-id: skycloak/v1alpha1/captchadomain
  labels:
    testing.upbound.io/example-name: login
  name: login
  namespace: crossplane-system
spec:
  forProvider:
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: production
    hostname: login.example.com
