/*
Copyright 2026 Decade Engineering
*/

// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ApplicationRoleAssignmentInitParameters struct {

	// (String) Application client ID receiving the role. Immutable.
	// Application client ID receiving the role. Immutable.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/cluster/skycloak/v1alpha1.Cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`

	// (String) Client ID owning the role, for a client role. Omit for a realm role. Immutable.
	// Client ID owning the role, for a client role. Omit for a realm role. Immutable.
	RoleClientID *string `json:"roleClientId,omitempty" tf:"role_client_id,omitempty"`

	// (String) Role name to assign. Immutable.
	// Role name to assign. Immutable.
	RoleName *string `json:"roleName,omitempty" tf:"role_name,omitempty"`
}

type ApplicationRoleAssignmentObservation struct {

	// (String) Application client ID receiving the role. Immutable.
	// Application client ID receiving the role. Immutable.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`

	// (String) Client ID owning the role, for a client role. Omit for a realm role. Immutable.
	// Client ID owning the role, for a client role. Omit for a realm role. Immutable.
	RoleClientID *string `json:"roleClientId,omitempty" tf:"role_client_id,omitempty"`

	// (String) Role name to assign. Immutable.
	// Role name to assign. Immutable.
	RoleName *string `json:"roleName,omitempty" tf:"role_name,omitempty"`
}

type ApplicationRoleAssignmentParameters struct {

	// (String) Application client ID receiving the role. Immutable.
	// Application client ID receiving the role. Immutable.
	// +kubebuilder:validation:Optional
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/cluster/skycloak/v1alpha1.Cluster
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	// +kubebuilder:validation:Optional
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`

	// (String) Client ID owning the role, for a client role. Omit for a realm role. Immutable.
	// Client ID owning the role, for a client role. Omit for a realm role. Immutable.
	// +kubebuilder:validation:Optional
	RoleClientID *string `json:"roleClientId,omitempty" tf:"role_client_id,omitempty"`

	// (String) Role name to assign. Immutable.
	// Role name to assign. Immutable.
	// +kubebuilder:validation:Optional
	RoleName *string `json:"roleName,omitempty" tf:"role_name,omitempty"`
}

// ApplicationRoleAssignmentSpec defines the desired state of ApplicationRoleAssignment
type ApplicationRoleAssignmentSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   ApplicationRoleAssignmentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ApplicationRoleAssignmentInitParameters `json:"initProvider,omitempty"`
}

// ApplicationRoleAssignmentStatus defines the observed state of ApplicationRoleAssignment.
type ApplicationRoleAssignmentStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ApplicationRoleAssignmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ApplicationRoleAssignment is the Schema for the ApplicationRoleAssignments API. Grants a role to an application's service account. One resource per (client, role) edge.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,skycloak}
type ApplicationRoleAssignment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.clientId) || (has(self.initProvider) && has(self.initProvider.clientId))",message="spec.forProvider.clientId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.realmName) || (has(self.initProvider) && has(self.initProvider.realmName))",message="spec.forProvider.realmName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.roleName) || (has(self.initProvider) && has(self.initProvider.roleName))",message="spec.forProvider.roleName is a required parameter"
	Spec   ApplicationRoleAssignmentSpec   `json:"spec"`
	Status ApplicationRoleAssignmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ApplicationRoleAssignmentList contains a list of ApplicationRoleAssignments
type ApplicationRoleAssignmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ApplicationRoleAssignment `json:"items"`
}

// Repository type metadata.
var (
	ApplicationRoleAssignment_Kind             = "ApplicationRoleAssignment"
	ApplicationRoleAssignment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ApplicationRoleAssignment_Kind}.String()
	ApplicationRoleAssignment_KindAPIVersion   = ApplicationRoleAssignment_Kind + "." + CRDGroupVersion.String()
	ApplicationRoleAssignment_GroupVersionKind = CRDGroupVersion.WithKind(ApplicationRoleAssignment_Kind)
)

func init() {
	SchemeBuilder.Register(&ApplicationRoleAssignment{}, &ApplicationRoleAssignmentList{})
}
