/*
Copyright 2026 Decade Engineering
*/

// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type BotManagementInitParameters struct {

	// agent regex patterns to always block.
	// User-agent regex patterns to always block.
	BlacklistedAgents []*string `json:"blacklistedAgents,omitempty" tf:"blacklisted_agents,omitempty"`

	// (String) none, javascript, or captcha.
	// `none`, `javascript`, or `captcha`.
	ChallengeMode *string `json:"challengeMode,omitempty" tf:"challenge_mode,omitempty"`

	// blocking is enabled.
	// Whether bot management is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) block or detect.
	// `block` or `detect`.
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// agent regex patterns to always allow.
	// User-agent regex patterns to always allow.
	WhitelistedAgents []*string `json:"whitelistedAgents,omitempty" tf:"whitelisted_agents,omitempty"`
}

type BotManagementObservation struct {

	// agent regex patterns to always block.
	// User-agent regex patterns to always block.
	BlacklistedAgents []*string `json:"blacklistedAgents,omitempty" tf:"blacklisted_agents,omitempty"`

	// (String) none, javascript, or captcha.
	// `none`, `javascript`, or `captcha`.
	ChallengeMode *string `json:"challengeMode,omitempty" tf:"challenge_mode,omitempty"`

	// blocking is enabled.
	// Whether bot management is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) block or detect.
	// `block` or `detect`.
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// agent regex patterns to always allow.
	// User-agent regex patterns to always allow.
	WhitelistedAgents []*string `json:"whitelistedAgents,omitempty" tf:"whitelisted_agents,omitempty"`
}

type BotManagementParameters struct {

	// agent regex patterns to always block.
	// User-agent regex patterns to always block.
	// +kubebuilder:validation:Optional
	BlacklistedAgents []*string `json:"blacklistedAgents,omitempty" tf:"blacklisted_agents,omitempty"`

	// (String) none, javascript, or captcha.
	// `none`, `javascript`, or `captcha`.
	// +kubebuilder:validation:Optional
	ChallengeMode *string `json:"challengeMode" tf:"challenge_mode,omitempty"`

	// blocking is enabled.
	// Whether bot management is enabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled" tf:"enabled,omitempty"`

	// (String) block or detect.
	// `block` or `detect`.
	// +kubebuilder:validation:Optional
	Mode *string `json:"mode" tf:"mode,omitempty"`

	// agent regex patterns to always allow.
	// User-agent regex patterns to always allow.
	// +kubebuilder:validation:Optional
	WhitelistedAgents []*string `json:"whitelistedAgents,omitempty" tf:"whitelisted_agents,omitempty"`
}

type CaptchaInitParameters struct {

	// blocking is enabled.
	// Whether CAPTCHA challenges are presented.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (List of String) Realm IDs where challenges are presented during login.
	// Realm IDs where challenges are presented during login.
	EnabledRealms []*string `json:"enabledRealms,omitempty" tf:"enabled_realms,omitempty"`
}

type CaptchaObservation struct {

	// blocking is enabled.
	// Whether CAPTCHA challenges are presented.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (List of String) Realm IDs where challenges are presented during login.
	// Realm IDs where challenges are presented during login.
	EnabledRealms []*string `json:"enabledRealms,omitempty" tf:"enabled_realms,omitempty"`
}

type CaptchaParameters struct {

	// blocking is enabled.
	// Whether CAPTCHA challenges are presented.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled" tf:"enabled,omitempty"`

	// (List of String) Realm IDs where challenges are presented during login.
	// Realm IDs where challenges are presented during login.
	// +kubebuilder:validation:Optional
	EnabledRealms []*string `json:"enabledRealms,omitempty" tf:"enabled_realms,omitempty"`
}

type CategoriesInitParameters struct {

	// (Boolean)
	CrossSiteScripting *bool `json:"crossSiteScripting,omitempty" tf:"cross_site_scripting,omitempty"`

	// (Boolean)
	DataLeakage *bool `json:"dataLeakage,omitempty" tf:"data_leakage,omitempty"`

	// (Boolean)
	JavaAttacks *bool `json:"javaAttacks,omitempty" tf:"java_attacks,omitempty"`

	// (Boolean)
	LocalFileInclusion *bool `json:"localFileInclusion,omitempty" tf:"local_file_inclusion,omitempty"`

	// (Boolean)
	PHPInjection *bool `json:"phpInjection,omitempty" tf:"php_injection,omitempty"`

	// (Boolean)
	ProtocolAttacks *bool `json:"protocolAttacks,omitempty" tf:"protocol_attacks,omitempty"`

	// (Boolean)
	ProtocolEnforcement *bool `json:"protocolEnforcement,omitempty" tf:"protocol_enforcement,omitempty"`

	// (Boolean)
	RemoteCodeExecution *bool `json:"remoteCodeExecution,omitempty" tf:"remote_code_execution,omitempty"`

	// (Boolean)
	RemoteFileInclusion *bool `json:"remoteFileInclusion,omitempty" tf:"remote_file_inclusion,omitempty"`

	// (Boolean)
	SQLInjection *bool `json:"sqlInjection,omitempty" tf:"sql_injection,omitempty"`

	// (Boolean)
	SessionFixation *bool `json:"sessionFixation,omitempty" tf:"session_fixation,omitempty"`

	// (Boolean)
	WebshellDetection *bool `json:"webshellDetection,omitempty" tf:"webshell_detection,omitempty"`
}

type CategoriesObservation struct {

	// (Boolean)
	CrossSiteScripting *bool `json:"crossSiteScripting,omitempty" tf:"cross_site_scripting,omitempty"`

	// (Boolean)
	DataLeakage *bool `json:"dataLeakage,omitempty" tf:"data_leakage,omitempty"`

	// (Boolean)
	JavaAttacks *bool `json:"javaAttacks,omitempty" tf:"java_attacks,omitempty"`

	// (Boolean)
	LocalFileInclusion *bool `json:"localFileInclusion,omitempty" tf:"local_file_inclusion,omitempty"`

	// (Boolean)
	PHPInjection *bool `json:"phpInjection,omitempty" tf:"php_injection,omitempty"`

	// (Boolean)
	ProtocolAttacks *bool `json:"protocolAttacks,omitempty" tf:"protocol_attacks,omitempty"`

	// (Boolean)
	ProtocolEnforcement *bool `json:"protocolEnforcement,omitempty" tf:"protocol_enforcement,omitempty"`

	// (Boolean)
	RemoteCodeExecution *bool `json:"remoteCodeExecution,omitempty" tf:"remote_code_execution,omitempty"`

	// (Boolean)
	RemoteFileInclusion *bool `json:"remoteFileInclusion,omitempty" tf:"remote_file_inclusion,omitempty"`

	// (Boolean)
	SQLInjection *bool `json:"sqlInjection,omitempty" tf:"sql_injection,omitempty"`

	// (Boolean)
	SessionFixation *bool `json:"sessionFixation,omitempty" tf:"session_fixation,omitempty"`

	// (Boolean)
	WebshellDetection *bool `json:"webshellDetection,omitempty" tf:"webshell_detection,omitempty"`
}

type CategoriesParameters struct {

	// (Boolean)
	// +kubebuilder:validation:Optional
	CrossSiteScripting *bool `json:"crossSiteScripting" tf:"cross_site_scripting,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	DataLeakage *bool `json:"dataLeakage" tf:"data_leakage,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	JavaAttacks *bool `json:"javaAttacks" tf:"java_attacks,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	LocalFileInclusion *bool `json:"localFileInclusion" tf:"local_file_inclusion,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	PHPInjection *bool `json:"phpInjection" tf:"php_injection,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	ProtocolAttacks *bool `json:"protocolAttacks" tf:"protocol_attacks,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	ProtocolEnforcement *bool `json:"protocolEnforcement" tf:"protocol_enforcement,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	RemoteCodeExecution *bool `json:"remoteCodeExecution" tf:"remote_code_execution,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	RemoteFileInclusion *bool `json:"remoteFileInclusion" tf:"remote_file_inclusion,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	SQLInjection *bool `json:"sqlInjection" tf:"sql_injection,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	SessionFixation *bool `json:"sessionFixation" tf:"session_fixation,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	WebshellDetection *bool `json:"webshellDetection" tf:"webshell_detection,omitempty"`
}

type ClusterSecurityInitParameters struct {

	// (Attributes) Bot detection and challenges. (see below for nested schema)
	BotManagement *BotManagementInitParameters `json:"botManagement,omitempty" tf:"bot_management,omitempty"`

	// flow CAPTCHA challenges. Omit to leave the server's CAPTCHA settings unmanaged. (see below for nested schema)
	Captcha *CaptchaInitParameters `json:"captcha,omitempty" tf:"captcha,omitempty"`

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/cluster/skycloak/v1alpha1.Cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// based access control. (see below for nested schema)
	GeoBlocking *GeoBlockingInitParameters `json:"geoBlocking,omitempty" tf:"geo_blocking,omitempty"`

	// path IP allow rules. (see below for nested schema)
	IPAccessControl []IPAccessControlInitParameters `json:"ipAccessControl,omitempty" tf:"ip_access_control,omitempty"`

	// rate ceilings. (see below for nested schema)
	RateLimiting *RateLimitingInitParameters `json:"rateLimiting,omitempty" tf:"rate_limiting,omitempty"`

	// (Attributes) Web application firewall. (see below for nested schema)
	Waf *WafInitParameters `json:"waf,omitempty" tf:"waf,omitempty"`
}

type ClusterSecurityObservation struct {

	// (Attributes) Bot detection and challenges. (see below for nested schema)
	BotManagement *BotManagementObservation `json:"botManagement,omitempty" tf:"bot_management,omitempty"`

	// flow CAPTCHA challenges. Omit to leave the server's CAPTCHA settings unmanaged. (see below for nested schema)
	Captcha *CaptchaObservation `json:"captcha,omitempty" tf:"captcha,omitempty"`

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// based access control. (see below for nested schema)
	GeoBlocking *GeoBlockingObservation `json:"geoBlocking,omitempty" tf:"geo_blocking,omitempty"`

	// (String) cluster_id/security.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// path IP allow rules. (see below for nested schema)
	IPAccessControl []IPAccessControlObservation `json:"ipAccessControl,omitempty" tf:"ip_access_control,omitempty"`

	// rate ceilings. (see below for nested schema)
	RateLimiting *RateLimitingObservation `json:"rateLimiting,omitempty" tf:"rate_limiting,omitempty"`

	// (Attributes) Web application firewall. (see below for nested schema)
	Waf *WafObservation `json:"waf,omitempty" tf:"waf,omitempty"`
}

type ClusterSecurityParameters struct {

	// (Attributes) Bot detection and challenges. (see below for nested schema)
	// +kubebuilder:validation:Optional
	BotManagement *BotManagementParameters `json:"botManagement,omitempty" tf:"bot_management,omitempty"`

	// flow CAPTCHA challenges. Omit to leave the server's CAPTCHA settings unmanaged. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Captcha *CaptchaParameters `json:"captcha,omitempty" tf:"captcha,omitempty"`

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/cluster/skycloak/v1alpha1.Cluster
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// based access control. (see below for nested schema)
	// +kubebuilder:validation:Optional
	GeoBlocking *GeoBlockingParameters `json:"geoBlocking,omitempty" tf:"geo_blocking,omitempty"`

	// path IP allow rules. (see below for nested schema)
	// +kubebuilder:validation:Optional
	IPAccessControl []IPAccessControlParameters `json:"ipAccessControl,omitempty" tf:"ip_access_control,omitempty"`

	// rate ceilings. (see below for nested schema)
	// +kubebuilder:validation:Optional
	RateLimiting *RateLimitingParameters `json:"rateLimiting,omitempty" tf:"rate_limiting,omitempty"`

	// (Attributes) Web application firewall. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Waf *WafParameters `json:"waf,omitempty" tf:"waf,omitempty"`
}

type EndpointLimitsInitParameters struct {

	// (String) URL path prefix to restrict.
	// URL path.
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// (Number) Max requests per minute.
	// Max requests per minute.
	Rpm *float64 `json:"rpm,omitempty" tf:"rpm,omitempty"`
}

type EndpointLimitsObservation struct {

	// (String) URL path prefix to restrict.
	// URL path.
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// (Number) Max requests per minute.
	// Max requests per minute.
	Rpm *float64 `json:"rpm,omitempty" tf:"rpm,omitempty"`
}

type EndpointLimitsParameters struct {

	// (String) URL path prefix to restrict.
	// URL path.
	// +kubebuilder:validation:Optional
	Path *string `json:"path" tf:"path,omitempty"`

	// (Number) Max requests per minute.
	// Max requests per minute.
	// +kubebuilder:validation:Optional
	Rpm *float64 `json:"rpm" tf:"rpm,omitempty"`
}

type GeoBlockingInitParameters struct {

	// 1 alpha-2 country codes.
	// ISO 3166-1 alpha-2 country codes.
	Countries []*string `json:"countries,omitempty" tf:"countries,omitempty"`

	// blocking is enabled.
	// Whether geo-blocking is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) allowlist or blocklist.
	// `allowlist` or `blocklist`.
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`
}

type GeoBlockingObservation struct {

	// 1 alpha-2 country codes.
	// ISO 3166-1 alpha-2 country codes.
	Countries []*string `json:"countries,omitempty" tf:"countries,omitempty"`

	// blocking is enabled.
	// Whether geo-blocking is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) allowlist or blocklist.
	// `allowlist` or `blocklist`.
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`
}

type GeoBlockingParameters struct {

	// 1 alpha-2 country codes.
	// ISO 3166-1 alpha-2 country codes.
	// +kubebuilder:validation:Optional
	Countries []*string `json:"countries" tf:"countries,omitempty"`

	// blocking is enabled.
	// Whether geo-blocking is enabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled" tf:"enabled,omitempty"`

	// (String) allowlist or blocklist.
	// `allowlist` or `blocklist`.
	// +kubebuilder:validation:Optional
	Mode *string `json:"mode" tf:"mode,omitempty"`
}

type IPAccessControlInitParameters struct {

	// (List of String) CIDR ranges to allow.
	// CIDR ranges to allow.
	AllowedCidrs []*string `json:"allowedCidrs,omitempty" tf:"allowed_cidrs,omitempty"`

	// (List of String) Individual IPs to allow.
	// Individual IPs to allow.
	AllowedIps []*string `json:"allowedIps,omitempty" tf:"allowed_ips,omitempty"`

	// (String) Rule description.
	// Rule description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) URL path prefix to restrict.
	// URL path prefix to restrict.
	Path *string `json:"path,omitempty" tf:"path,omitempty"`
}

type IPAccessControlObservation struct {

	// (List of String) CIDR ranges to allow.
	// CIDR ranges to allow.
	AllowedCidrs []*string `json:"allowedCidrs,omitempty" tf:"allowed_cidrs,omitempty"`

	// (List of String) Individual IPs to allow.
	// Individual IPs to allow.
	AllowedIps []*string `json:"allowedIps,omitempty" tf:"allowed_ips,omitempty"`

	// (String) Rule description.
	// Rule description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) URL path prefix to restrict.
	// URL path prefix to restrict.
	Path *string `json:"path,omitempty" tf:"path,omitempty"`
}

type IPAccessControlParameters struct {

	// (List of String) CIDR ranges to allow.
	// CIDR ranges to allow.
	// +kubebuilder:validation:Optional
	AllowedCidrs []*string `json:"allowedCidrs,omitempty" tf:"allowed_cidrs,omitempty"`

	// (List of String) Individual IPs to allow.
	// Individual IPs to allow.
	// +kubebuilder:validation:Optional
	AllowedIps []*string `json:"allowedIps,omitempty" tf:"allowed_ips,omitempty"`

	// (String) Rule description.
	// Rule description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) URL path prefix to restrict.
	// URL path prefix to restrict.
	// +kubebuilder:validation:Optional
	Path *string `json:"path" tf:"path,omitempty"`
}

type RateLimitingInitParameters struct {

	// blocking is enabled.
	// Whether rate limiting is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// path request limits. (see below for nested schema)
	EndpointLimits []EndpointLimitsInitParameters `json:"endpointLimits,omitempty" tf:"endpoint_limits,omitempty"`

	// per-minute ceiling.
	// Global requests-per-minute ceiling.
	GlobalRpm *float64 `json:"globalRpm,omitempty" tf:"global_rpm,omitempty"`

	// source-IP requests-per-minute ceiling.
	// Per-source-IP requests-per-minute ceiling.
	PerIPRpm *float64 `json:"perIpRpm,omitempty" tf:"per_ip_rpm,omitempty"`
}

type RateLimitingObservation struct {

	// blocking is enabled.
	// Whether rate limiting is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// path request limits. (see below for nested schema)
	EndpointLimits []EndpointLimitsObservation `json:"endpointLimits,omitempty" tf:"endpoint_limits,omitempty"`

	// per-minute ceiling.
	// Global requests-per-minute ceiling.
	GlobalRpm *float64 `json:"globalRpm,omitempty" tf:"global_rpm,omitempty"`

	// source-IP requests-per-minute ceiling.
	// Per-source-IP requests-per-minute ceiling.
	PerIPRpm *float64 `json:"perIpRpm,omitempty" tf:"per_ip_rpm,omitempty"`
}

type RateLimitingParameters struct {

	// blocking is enabled.
	// Whether rate limiting is enabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled" tf:"enabled,omitempty"`

	// path request limits. (see below for nested schema)
	// +kubebuilder:validation:Optional
	EndpointLimits []EndpointLimitsParameters `json:"endpointLimits,omitempty" tf:"endpoint_limits,omitempty"`

	// per-minute ceiling.
	// Global requests-per-minute ceiling.
	// +kubebuilder:validation:Optional
	GlobalRpm *float64 `json:"globalRpm,omitempty" tf:"global_rpm,omitempty"`

	// source-IP requests-per-minute ceiling.
	// Per-source-IP requests-per-minute ceiling.
	// +kubebuilder:validation:Optional
	PerIPRpm *float64 `json:"perIpRpm,omitempty" tf:"per_ip_rpm,omitempty"`
}

type RuleExclusionsInitParameters struct {

	// (List of String) Restrict the exclusion to these paths.
	// Restrict the exclusion to these paths.
	Paths []*string `json:"paths,omitempty" tf:"paths,omitempty"`

	// (List of String) OWASP CRS rule IDs to disable.
	// OWASP CRS rule IDs to disable.
	RuleIds []*string `json:"ruleIds,omitempty" tf:"rule_ids,omitempty"`
}

type RuleExclusionsObservation struct {

	// (List of String) Restrict the exclusion to these paths.
	// Restrict the exclusion to these paths.
	Paths []*string `json:"paths,omitempty" tf:"paths,omitempty"`

	// (List of String) OWASP CRS rule IDs to disable.
	// OWASP CRS rule IDs to disable.
	RuleIds []*string `json:"ruleIds,omitempty" tf:"rule_ids,omitempty"`
}

type RuleExclusionsParameters struct {

	// (List of String) Restrict the exclusion to these paths.
	// Restrict the exclusion to these paths.
	// +kubebuilder:validation:Optional
	Paths []*string `json:"paths,omitempty" tf:"paths,omitempty"`

	// (List of String) OWASP CRS rule IDs to disable.
	// OWASP CRS rule IDs to disable.
	// +kubebuilder:validation:Optional
	RuleIds []*string `json:"ruleIds" tf:"rule_ids,omitempty"`
}

type WafInitParameters struct {

	// (Attributes) Active rule categories . (see below for nested schema)
	Categories *CategoriesInitParameters `json:"categories,omitempty" tf:"categories,omitempty"`

	// blocking is enabled.
	// Whether the WAF is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (List of String) URL paths exempt from inspection.
	// URL paths exempt from inspection.
	ExclusionPaths []*string `json:"exclusionPaths,omitempty" tf:"exclusion_paths,omitempty"`

	// (String) block or detect.
	// `block` or `detect`.
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// 4).
	// Detection sensitivity (1-4).
	ParanoiaLevel *float64 `json:"paranoiaLevel,omitempty" tf:"paranoia_level,omitempty"`

	// (String) owasp_top_10, full_crs, or custom.
	// `owasp_top_10`, `full_crs`, or `custom`.
	Preset *string `json:"preset,omitempty" tf:"preset,omitempty"`

	// (Attributes List) CRS rules to disable. (see below for nested schema)
	RuleExclusions []RuleExclusionsInitParameters `json:"ruleExclusions,omitempty" tf:"rule_exclusions,omitempty"`
}

type WafObservation struct {

	// (Attributes) Active rule categories . (see below for nested schema)
	Categories *CategoriesObservation `json:"categories,omitempty" tf:"categories,omitempty"`

	// blocking is enabled.
	// Whether the WAF is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (List of String) URL paths exempt from inspection.
	// URL paths exempt from inspection.
	ExclusionPaths []*string `json:"exclusionPaths,omitempty" tf:"exclusion_paths,omitempty"`

	// (String) block or detect.
	// `block` or `detect`.
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// 4).
	// Detection sensitivity (1-4).
	ParanoiaLevel *float64 `json:"paranoiaLevel,omitempty" tf:"paranoia_level,omitempty"`

	// (String) owasp_top_10, full_crs, or custom.
	// `owasp_top_10`, `full_crs`, or `custom`.
	Preset *string `json:"preset,omitempty" tf:"preset,omitempty"`

	// (Attributes List) CRS rules to disable. (see below for nested schema)
	RuleExclusions []RuleExclusionsObservation `json:"ruleExclusions,omitempty" tf:"rule_exclusions,omitempty"`
}

type WafParameters struct {

	// (Attributes) Active rule categories . (see below for nested schema)
	// +kubebuilder:validation:Optional
	Categories *CategoriesParameters `json:"categories,omitempty" tf:"categories,omitempty"`

	// blocking is enabled.
	// Whether the WAF is enabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled" tf:"enabled,omitempty"`

	// (List of String) URL paths exempt from inspection.
	// URL paths exempt from inspection.
	// +kubebuilder:validation:Optional
	ExclusionPaths []*string `json:"exclusionPaths,omitempty" tf:"exclusion_paths,omitempty"`

	// (String) block or detect.
	// `block` or `detect`.
	// +kubebuilder:validation:Optional
	Mode *string `json:"mode" tf:"mode,omitempty"`

	// 4).
	// Detection sensitivity (1-4).
	// +kubebuilder:validation:Optional
	ParanoiaLevel *float64 `json:"paranoiaLevel" tf:"paranoia_level,omitempty"`

	// (String) owasp_top_10, full_crs, or custom.
	// `owasp_top_10`, `full_crs`, or `custom`.
	// +kubebuilder:validation:Optional
	Preset *string `json:"preset" tf:"preset,omitempty"`

	// (Attributes List) CRS rules to disable. (see below for nested schema)
	// +kubebuilder:validation:Optional
	RuleExclusions []RuleExclusionsParameters `json:"ruleExclusions,omitempty" tf:"rule_exclusions,omitempty"`
}

// ClusterSecuritySpec defines the desired state of ClusterSecurity
type ClusterSecuritySpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   ClusterSecurityParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ClusterSecurityInitParameters `json:"initProvider,omitempty"`
}

// ClusterSecurityStatus defines the observed state of ClusterSecurity.
type ClusterSecurityStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ClusterSecurityObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ClusterSecurity is the Schema for the ClusterSecuritys API. Edge-security configuration for a cluster: IP allow-listing, rate limiting, WAF, geo-blocking, bot management, and CAPTCHA. A singleton per cluster. When the captcha block is omitted, the server's CAPTCHA settings are left untouched. CAPTCHA hostnames are registered via skycloak_captcha_domain.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,skycloak}
type ClusterSecurity struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ClusterSecuritySpec   `json:"spec"`
	Status            ClusterSecurityStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ClusterSecurityList contains a list of ClusterSecuritys
type ClusterSecurityList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ClusterSecurity `json:"items"`
}

// Repository type metadata.
var (
	ClusterSecurity_Kind             = "ClusterSecurity"
	ClusterSecurity_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ClusterSecurity_Kind}.String()
	ClusterSecurity_KindAPIVersion   = ClusterSecurity_Kind + "." + CRDGroupVersion.String()
	ClusterSecurity_GroupVersionKind = CRDGroupVersion.WithKind(ClusterSecurity_Kind)
)

func init() {
	SchemeBuilder.Register(&ClusterSecurity{}, &ClusterSecurityList{})
}
