/*
Copyright 2026 Decade Engineering
*/

// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type CustomExtensionInitParameters struct {

	// (String) Extension description.
	// Extension description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Icon URL.
	// Icon URL.
	IconURL *string `json:"iconUrl,omitempty" tf:"icon_url,omitempty"`

	// (String) Path to the extension JAR file.
	// Path to the extension JAR file.
	Jar *string `json:"jar,omitempty" tf:"jar,omitempty"`

	// (String) Keycloak major version this JAR targets (e.g. 26).
	// Keycloak major version this JAR targets (e.g. `26`).
	KeycloakVersion *string `json:"keycloakVersion,omitempty" tf:"keycloak_version,omitempty"`

	// (String) Extension name.
	// Extension name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) How parameters are supplied to the extension.
	// How parameters are supplied to the extension.
	ParameterType *string `json:"parameterType,omitempty" tf:"parameter_type,omitempty"`

	// (Attributes List) Configuration parameter schema exposed when installing the extension. (see below for nested schema)
	Parameters []ParametersInitParameters `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// (String) Source repository URL.
	// Source repository URL.
	RepositoryURL *string `json:"repositoryUrl,omitempty" tf:"repository_url,omitempty"`

	// (String) Semantic version (e.g. 1.0.0). Bump it together with the JAR to publish a new version.
	// Semantic version (e.g. `1.0.0`). Bump it together with the JAR to publish a new version.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type CustomExtensionObservation struct {

	// 256 of the uploaded JAR. Recomputed each plan; a change publishes a new version.
	// SHA-256 of the uploaded JAR. Recomputed each plan; a change publishes a new version.
	ContentSha256 *string `json:"contentSha256,omitempty" tf:"content_sha256,omitempty"`

	// (String) Creation timestamp (RFC 3339).
	// Creation timestamp (RFC 3339).
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) Extension description.
	// Extension description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Extension ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Icon URL.
	// Icon URL.
	IconURL *string `json:"iconUrl,omitempty" tf:"icon_url,omitempty"`

	// (String) Path to the extension JAR file.
	// Path to the extension JAR file.
	Jar *string `json:"jar,omitempty" tf:"jar,omitempty"`

	// (String) Keycloak major version this JAR targets (e.g. 26).
	// Keycloak major version this JAR targets (e.g. `26`).
	KeycloakVersion *string `json:"keycloakVersion,omitempty" tf:"keycloak_version,omitempty"`

	// (String) Extension name.
	// Extension name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) How parameters are supplied to the extension.
	// How parameters are supplied to the extension.
	ParameterType *string `json:"parameterType,omitempty" tf:"parameter_type,omitempty"`

	// (Attributes List) Configuration parameter schema exposed when installing the extension. (see below for nested schema)
	Parameters []ParametersObservation `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// (String) Source repository URL.
	// Source repository URL.
	RepositoryURL *string `json:"repositoryUrl,omitempty" tf:"repository_url,omitempty"`

	// (String) Malware scan result.
	// Malware scan result.
	ScanStatus *string `json:"scanStatus,omitempty" tf:"scan_status,omitempty"`

	// (String) Extension source (always custom for this resource).
	// Extension source (always `custom` for this resource).
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// (String) Last update timestamp (RFC 3339).
	// Last update timestamp (RFC 3339).
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// (String) Semantic version (e.g. 1.0.0). Bump it together with the JAR to publish a new version.
	// Semantic version (e.g. `1.0.0`). Bump it together with the JAR to publish a new version.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type CustomExtensionParameters struct {

	// (String) Extension description.
	// Extension description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Icon URL.
	// Icon URL.
	// +kubebuilder:validation:Optional
	IconURL *string `json:"iconUrl,omitempty" tf:"icon_url,omitempty"`

	// (String) Path to the extension JAR file.
	// Path to the extension JAR file.
	// +kubebuilder:validation:Optional
	Jar *string `json:"jar,omitempty" tf:"jar,omitempty"`

	// (String) Keycloak major version this JAR targets (e.g. 26).
	// Keycloak major version this JAR targets (e.g. `26`).
	// +kubebuilder:validation:Optional
	KeycloakVersion *string `json:"keycloakVersion,omitempty" tf:"keycloak_version,omitempty"`

	// (String) Extension name.
	// Extension name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) How parameters are supplied to the extension.
	// How parameters are supplied to the extension.
	// +kubebuilder:validation:Optional
	ParameterType *string `json:"parameterType,omitempty" tf:"parameter_type,omitempty"`

	// (Attributes List) Configuration parameter schema exposed when installing the extension. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Parameters []ParametersParameters `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// (String) Source repository URL.
	// Source repository URL.
	// +kubebuilder:validation:Optional
	RepositoryURL *string `json:"repositoryUrl,omitempty" tf:"repository_url,omitempty"`

	// (String) Semantic version (e.g. 1.0.0). Bump it together with the JAR to publish a new version.
	// Semantic version (e.g. `1.0.0`). Bump it together with the JAR to publish a new version.
	// +kubebuilder:validation:Optional
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type OptionsInitParameters struct {

	// readable label.
	// Option label.
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// (String) Option value.
	// Option value.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type OptionsObservation struct {

	// readable label.
	// Option label.
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// (String) Option value.
	// Option value.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type OptionsParameters struct {

	// readable label.
	// Option label.
	// +kubebuilder:validation:Optional
	Label *string `json:"label" tf:"label,omitempty"`

	// (String) Option value.
	// Option value.
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

type ParametersInitParameters struct {

	// (String) Default value.
	// Default value.
	DefaultValue *string `json:"defaultValue,omitempty" tf:"default_value,omitempty"`

	// only/secret.
	// Whether the value is write-only/secret.
	IsSensitive *bool `json:"isSensitive,omitempty" tf:"is_sensitive,omitempty"`

	// (String) Unique parameter identifier.
	// Unique parameter identifier.
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// readable label.
	// Human-readable label.
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// (Attributes List) Choices for a dropdown parameter. (see below for nested schema)
	Options []OptionsInitParameters `json:"options,omitempty" tf:"options,omitempty"`

	// (Boolean) Whether the parameter must be supplied.
	// Whether the parameter must be supplied.
	Required *bool `json:"required,omitempty" tf:"required,omitempty"`

	// (String) Field type: text, password, number, checkbox, or dropdown.
	// Field type: `text`, `password`, `number`, `checkbox`, or `dropdown`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ParametersObservation struct {

	// (String) Default value.
	// Default value.
	DefaultValue *string `json:"defaultValue,omitempty" tf:"default_value,omitempty"`

	// only/secret.
	// Whether the value is write-only/secret.
	IsSensitive *bool `json:"isSensitive,omitempty" tf:"is_sensitive,omitempty"`

	// (String) Unique parameter identifier.
	// Unique parameter identifier.
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// readable label.
	// Human-readable label.
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// (Attributes List) Choices for a dropdown parameter. (see below for nested schema)
	Options []OptionsObservation `json:"options,omitempty" tf:"options,omitempty"`

	// (Boolean) Whether the parameter must be supplied.
	// Whether the parameter must be supplied.
	Required *bool `json:"required,omitempty" tf:"required,omitempty"`

	// (String) Field type: text, password, number, checkbox, or dropdown.
	// Field type: `text`, `password`, `number`, `checkbox`, or `dropdown`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ParametersParameters struct {

	// (String) Default value.
	// Default value.
	// +kubebuilder:validation:Optional
	DefaultValue *string `json:"defaultValue,omitempty" tf:"default_value,omitempty"`

	// only/secret.
	// Whether the value is write-only/secret.
	// +kubebuilder:validation:Optional
	IsSensitive *bool `json:"isSensitive,omitempty" tf:"is_sensitive,omitempty"`

	// (String) Unique parameter identifier.
	// Unique parameter identifier.
	// +kubebuilder:validation:Optional
	Key *string `json:"key" tf:"key,omitempty"`

	// readable label.
	// Human-readable label.
	// +kubebuilder:validation:Optional
	Label *string `json:"label" tf:"label,omitempty"`

	// (Attributes List) Choices for a dropdown parameter. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Options []OptionsParameters `json:"options,omitempty" tf:"options,omitempty"`

	// (Boolean) Whether the parameter must be supplied.
	// Whether the parameter must be supplied.
	// +kubebuilder:validation:Optional
	Required *bool `json:"required,omitempty" tf:"required,omitempty"`

	// (String) Field type: text, password, number, checkbox, or dropdown.
	// Field type: `text`, `password`, `number`, `checkbox`, or `dropdown`.
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

// CustomExtensionSpec defines the desired state of CustomExtension
type CustomExtensionSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   CustomExtensionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CustomExtensionInitParameters `json:"initProvider,omitempty"`
}

// CustomExtensionStatus defines the observed state of CustomExtension.
type CustomExtensionStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               CustomExtensionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CustomExtension is the Schema for the CustomExtensions API. Uploads a custom Keycloak extension JAR to the workspace catalog. Changing the JAR contents or version publishes a new version; other metadata updates in place. Install it on a cluster with skycloak_cluster_extension.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,skycloak}
type CustomExtension struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.jar) || (has(self.initProvider) && has(self.initProvider.jar))",message="spec.forProvider.jar is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.keycloakVersion) || (has(self.initProvider) && has(self.initProvider.keycloakVersion))",message="spec.forProvider.keycloakVersion is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.version) || (has(self.initProvider) && has(self.initProvider.version))",message="spec.forProvider.version is a required parameter"
	Spec   CustomExtensionSpec   `json:"spec"`
	Status CustomExtensionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CustomExtensionList contains a list of CustomExtensions
type CustomExtensionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CustomExtension `json:"items"`
}

// Repository type metadata.
var (
	CustomExtension_Kind             = "CustomExtension"
	CustomExtension_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CustomExtension_Kind}.String()
	CustomExtension_KindAPIVersion   = CustomExtension_Kind + "." + CRDGroupVersion.String()
	CustomExtension_GroupVersionKind = CRDGroupVersion.WithKind(CustomExtension_Kind)
)

func init() {
	SchemeBuilder.Register(&CustomExtension{}, &CustomExtensionList{})
}
