/*
Copyright 2026 Decade Engineering
*/

// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ClusterMaintenanceWindowInitParameters struct {

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/cluster/skycloak/v1alpha1.Cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (List of Number) Days of week the window applies to (0 = Sunday ... 6 = Saturday).
	// Days of week the window applies to (0 = Sunday ... 6 = Saturday).
	DaysOfWeek []*float64 `json:"daysOfWeek,omitempty" tf:"days_of_week,omitempty"`

	// (Boolean) Whether the window is active.
	// Whether the window is active.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Local end time, HH:MM.
	// Local end time, `HH:MM`.
	EndLocal *string `json:"endLocal,omitempty" tf:"end_local,omitempty"`

	// (String) Local start time, HH:MM.
	// Local start time, `HH:MM`.
	StartLocal *string `json:"startLocal,omitempty" tf:"start_local,omitempty"`

	// (String) IANA timezone, e.g. Europe/Berlin.
	// IANA timezone, e.g. `Europe/Berlin`.
	Timezone *string `json:"timezone,omitempty" tf:"timezone,omitempty"`
}

type ClusterMaintenanceWindowObservation struct {

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (List of Number) Days of week the window applies to (0 = Sunday ... 6 = Saturday).
	// Days of week the window applies to (0 = Sunday ... 6 = Saturday).
	DaysOfWeek []*float64 `json:"daysOfWeek,omitempty" tf:"days_of_week,omitempty"`

	// (Boolean) Whether the window is active.
	// Whether the window is active.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Local end time, HH:MM.
	// Local end time, `HH:MM`.
	EndLocal *string `json:"endLocal,omitempty" tf:"end_local,omitempty"`

	// window.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Local start time, HH:MM.
	// Local start time, `HH:MM`.
	StartLocal *string `json:"startLocal,omitempty" tf:"start_local,omitempty"`

	// (String) IANA timezone, e.g. Europe/Berlin.
	// IANA timezone, e.g. `Europe/Berlin`.
	Timezone *string `json:"timezone,omitempty" tf:"timezone,omitempty"`
}

type ClusterMaintenanceWindowParameters struct {

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/cluster/skycloak/v1alpha1.Cluster
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (List of Number) Days of week the window applies to (0 = Sunday ... 6 = Saturday).
	// Days of week the window applies to (0 = Sunday ... 6 = Saturday).
	// +kubebuilder:validation:Optional
	DaysOfWeek []*float64 `json:"daysOfWeek,omitempty" tf:"days_of_week,omitempty"`

	// (Boolean) Whether the window is active.
	// Whether the window is active.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Local end time, HH:MM.
	// Local end time, `HH:MM`.
	// +kubebuilder:validation:Optional
	EndLocal *string `json:"endLocal,omitempty" tf:"end_local,omitempty"`

	// (String) Local start time, HH:MM.
	// Local start time, `HH:MM`.
	// +kubebuilder:validation:Optional
	StartLocal *string `json:"startLocal,omitempty" tf:"start_local,omitempty"`

	// (String) IANA timezone, e.g. Europe/Berlin.
	// IANA timezone, e.g. `Europe/Berlin`.
	// +kubebuilder:validation:Optional
	Timezone *string `json:"timezone,omitempty" tf:"timezone,omitempty"`
}

// ClusterMaintenanceWindowSpec defines the desired state of ClusterMaintenanceWindow
type ClusterMaintenanceWindowSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   ClusterMaintenanceWindowParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ClusterMaintenanceWindowInitParameters `json:"initProvider,omitempty"`
}

// ClusterMaintenanceWindowStatus defines the observed state of ClusterMaintenanceWindow.
type ClusterMaintenanceWindowStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ClusterMaintenanceWindowObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ClusterMaintenanceWindow is the Schema for the ClusterMaintenanceWindows API. The cluster's own maintenance window: when Skycloak applies upgrades and other disruptive changes. A singleton per cluster (create == update upsert). Destroying this resource does not leave the cluster without a window: it reverts the cluster to the workspace default window.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,skycloak}
type ClusterMaintenanceWindow struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.daysOfWeek) || (has(self.initProvider) && has(self.initProvider.daysOfWeek))",message="spec.forProvider.daysOfWeek is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.enabled) || (has(self.initProvider) && has(self.initProvider.enabled))",message="spec.forProvider.enabled is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.endLocal) || (has(self.initProvider) && has(self.initProvider.endLocal))",message="spec.forProvider.endLocal is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.startLocal) || (has(self.initProvider) && has(self.initProvider.startLocal))",message="spec.forProvider.startLocal is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.timezone) || (has(self.initProvider) && has(self.initProvider.timezone))",message="spec.forProvider.timezone is a required parameter"
	Spec   ClusterMaintenanceWindowSpec   `json:"spec"`
	Status ClusterMaintenanceWindowStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ClusterMaintenanceWindowList contains a list of ClusterMaintenanceWindows
type ClusterMaintenanceWindowList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ClusterMaintenanceWindow `json:"items"`
}

// Repository type metadata.
var (
	ClusterMaintenanceWindow_Kind             = "ClusterMaintenanceWindow"
	ClusterMaintenanceWindow_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ClusterMaintenanceWindow_Kind}.String()
	ClusterMaintenanceWindow_KindAPIVersion   = ClusterMaintenanceWindow_Kind + "." + CRDGroupVersion.String()
	ClusterMaintenanceWindow_GroupVersionKind = CRDGroupVersion.WithKind(ClusterMaintenanceWindow_Kind)
)

func init() {
	SchemeBuilder.Register(&ClusterMaintenanceWindow{}, &ClusterMaintenanceWindowList{})
}
