/*
Copyright 2026 Decade Engineering
*/

// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type CustomThemeInitParameters struct {

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/cluster/skycloak/v1alpha1.Cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (String) Theme description.
	// Theme description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Theme name.
	// Theme name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Path to the theme archive (.zip or .jar).
	// Path to the theme archive (`.zip` or `.jar`).
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// (List of String) Subset of theme types to deploy (login, account, admin, email). Omit to deploy all detected types. Immutable.
	// Subset of theme types to deploy (`login`, `account`, `admin`, `email`). Omit to deploy all detected types. Immutable.
	ThemeTypes []*string `json:"themeTypes,omitempty" tf:"theme_types,omitempty"`

	// (String) Semantic version (e.g. 1.2.3).
	// Semantic version (e.g. `1.2.3`).
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type CustomThemeObservation struct {

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// 256 of the uploaded file. Recomputed each plan; a change recreates the theme.
	// SHA-256 of the uploaded file. Recomputed each plan; a change recreates the theme.
	ContentSha256 *string `json:"contentSha256,omitempty" tf:"content_sha256,omitempty"`

	// (String) Last successful deployment timestamp (RFC 3339).
	// Last successful deployment timestamp (RFC 3339).
	DeployedAt *string `json:"deployedAt,omitempty" tf:"deployed_at,omitempty"`

	// (String) Theme description.
	// Theme description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Number) Size of the uploaded archive in bytes.
	// Size of the uploaded archive in bytes.
	FileSize *float64 `json:"fileSize,omitempty" tf:"file_size,omitempty"`

	// (String) Theme ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Theme name.
	// Theme name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Path to the theme archive (.zip or .jar).
	// Path to the theme archive (`.zip` or `.jar`).
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// (String) Deployment status (deployed, deploying, failed, undeploying).
	// Deployment status (`deployed`, `deploying`, `failed`, `undeploying`).
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (List of String) Subset of theme types to deploy (login, account, admin, email). Omit to deploy all detected types. Immutable.
	// Subset of theme types to deploy (`login`, `account`, `admin`, `email`). Omit to deploy all detected types. Immutable.
	ThemeTypes []*string `json:"themeTypes,omitempty" tf:"theme_types,omitempty"`

	// (String) Semantic version (e.g. 1.2.3).
	// Semantic version (e.g. `1.2.3`).
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type CustomThemeParameters struct {

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/cluster/skycloak/v1alpha1.Cluster
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (String) Theme description.
	// Theme description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Theme name.
	// Theme name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Path to the theme archive (.zip or .jar).
	// Path to the theme archive (`.zip` or `.jar`).
	// +kubebuilder:validation:Optional
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// (List of String) Subset of theme types to deploy (login, account, admin, email). Omit to deploy all detected types. Immutable.
	// Subset of theme types to deploy (`login`, `account`, `admin`, `email`). Omit to deploy all detected types. Immutable.
	// +kubebuilder:validation:Optional
	ThemeTypes []*string `json:"themeTypes,omitempty" tf:"theme_types,omitempty"`

	// (String) Semantic version (e.g. 1.2.3).
	// Semantic version (e.g. `1.2.3`).
	// +kubebuilder:validation:Optional
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

// CustomThemeSpec defines the desired state of CustomTheme
type CustomThemeSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   CustomThemeParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CustomThemeInitParameters `json:"initProvider,omitempty"`
}

// CustomThemeStatus defines the observed state of CustomTheme.
type CustomThemeStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               CustomThemeObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CustomTheme is the Schema for the CustomThemes API. Uploads a custom Keycloak theme (ZIP or Keycloakify JAR) to a cluster. Replacing the file contents or theme_types recreates the theme; name, description, and version update in place.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,skycloak}
type CustomTheme struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.source) || (has(self.initProvider) && has(self.initProvider.source))",message="spec.forProvider.source is a required parameter"
	Spec   CustomThemeSpec   `json:"spec"`
	Status CustomThemeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CustomThemeList contains a list of CustomThemes
type CustomThemeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CustomTheme `json:"items"`
}

// Repository type metadata.
var (
	CustomTheme_Kind             = "CustomTheme"
	CustomTheme_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CustomTheme_Kind}.String()
	CustomTheme_KindAPIVersion   = CustomTheme_Kind + "." + CRDGroupVersion.String()
	CustomTheme_GroupVersionKind = CRDGroupVersion.WithKind(CustomTheme_Kind)
)

func init() {
	SchemeBuilder.Register(&CustomTheme{}, &CustomThemeList{})
}
