/*
Copyright 2026 Decade Engineering
*/

// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ClientThemeAssignmentInitParameters struct {

	// (String) OIDC/SAML client ID. Immutable.
	// OIDC/SAML client ID. Immutable.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/cluster/skycloak/v1alpha1.Cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (String) Custom theme ID to activate for this client's login page. Omit to use the realm default.
	// Custom theme ID to activate for this client's login page. Omit to use the realm default.
	Login *string `json:"login,omitempty" tf:"login,omitempty"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`
}

type ClientThemeAssignmentObservation struct {

	// (String) OIDC/SAML client ID. Immutable.
	// OIDC/SAML client ID. Immutable.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (String) Composite ID cluster_id/realm_name/client_id/theme.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Custom theme ID to activate for this client's login page. Omit to use the realm default.
	// Custom theme ID to activate for this client's login page. Omit to use the realm default.
	Login *string `json:"login,omitempty" tf:"login,omitempty"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`
}

type ClientThemeAssignmentParameters struct {

	// (String) OIDC/SAML client ID. Immutable.
	// OIDC/SAML client ID. Immutable.
	// +kubebuilder:validation:Optional
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/cluster/skycloak/v1alpha1.Cluster
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (String) Custom theme ID to activate for this client's login page. Omit to use the realm default.
	// Custom theme ID to activate for this client's login page. Omit to use the realm default.
	// +kubebuilder:validation:Optional
	Login *string `json:"login,omitempty" tf:"login,omitempty"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	// +kubebuilder:validation:Optional
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`
}

// ClientThemeAssignmentSpec defines the desired state of ClientThemeAssignment
type ClientThemeAssignmentSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   ClientThemeAssignmentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ClientThemeAssignmentInitParameters `json:"initProvider,omitempty"`
}

// ClientThemeAssignmentStatus defines the observed state of ClientThemeAssignment.
type ClientThemeAssignmentStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ClientThemeAssignmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ClientThemeAssignment is the Schema for the ClientThemeAssignments API. Per-client login-theme override. Overrides the realm default for a single OIDC/SAML client.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,skycloak}
type ClientThemeAssignment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.clientId) || (has(self.initProvider) && has(self.initProvider.clientId))",message="spec.forProvider.clientId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.realmName) || (has(self.initProvider) && has(self.initProvider.realmName))",message="spec.forProvider.realmName is a required parameter"
	Spec   ClientThemeAssignmentSpec   `json:"spec"`
	Status ClientThemeAssignmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ClientThemeAssignmentList contains a list of ClientThemeAssignments
type ClientThemeAssignmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ClientThemeAssignment `json:"items"`
}

// Repository type metadata.
var (
	ClientThemeAssignment_Kind             = "ClientThemeAssignment"
	ClientThemeAssignment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ClientThemeAssignment_Kind}.String()
	ClientThemeAssignment_KindAPIVersion   = ClientThemeAssignment_Kind + "." + CRDGroupVersion.String()
	ClientThemeAssignment_GroupVersionKind = CRDGroupVersion.WithKind(ClientThemeAssignment_Kind)
)

func init() {
	SchemeBuilder.Register(&ClientThemeAssignment{}, &ClientThemeAssignmentList{})
}
