/*
Copyright 2026 Decade Engineering
*/

// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type CaptchaDomainInitParameters struct {

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/cluster/skycloak/v1alpha1.Cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (String) Hostname to protect; must be one of the cluster's verified custom domains. Immutable.
	// Hostname to protect; must be one of the cluster's verified custom domains. Immutable.
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`
}

type CaptchaDomainObservation struct {

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (String) Registration timestamp.
	// Registration timestamp.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) Hostname to protect; must be one of the cluster's verified custom domains. Immutable.
	// Hostname to protect; must be one of the cluster's verified custom domains. Immutable.
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// (String) Composite ID cluster_id/hostname.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type CaptchaDomainParameters struct {

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/cluster/skycloak/v1alpha1.Cluster
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (String) Hostname to protect; must be one of the cluster's verified custom domains. Immutable.
	// Hostname to protect; must be one of the cluster's verified custom domains. Immutable.
	// +kubebuilder:validation:Optional
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`
}

// CaptchaDomainSpec defines the desired state of CaptchaDomain
type CaptchaDomainSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   CaptchaDomainParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CaptchaDomainInitParameters `json:"initProvider,omitempty"`
}

// CaptchaDomainStatus defines the observed state of CaptchaDomain.
type CaptchaDomainStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               CaptchaDomainObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CaptchaDomain is the Schema for the CaptchaDomains API. A hostname registered for CAPTCHA protection on a cluster. The number of registrable hostnames is capped per cluster; the API rejects additions beyond the cap.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,skycloak}
type CaptchaDomain struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.hostname) || (has(self.initProvider) && has(self.initProvider.hostname))",message="spec.forProvider.hostname is a required parameter"
	Spec   CaptchaDomainSpec   `json:"spec"`
	Status CaptchaDomainStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CaptchaDomainList contains a list of CaptchaDomains
type CaptchaDomainList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CaptchaDomain `json:"items"`
}

// Repository type metadata.
var (
	CaptchaDomain_Kind             = "CaptchaDomain"
	CaptchaDomain_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CaptchaDomain_Kind}.String()
	CaptchaDomain_KindAPIVersion   = CaptchaDomain_Kind + "." + CRDGroupVersion.String()
	CaptchaDomain_GroupVersionKind = CRDGroupVersion.WithKind(CaptchaDomain_Kind)
)

func init() {
	SchemeBuilder.Register(&CaptchaDomain{}, &CaptchaDomainList{})
}
