/*
Copyright 2026 Decade Engineering
*/

// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type DomainRouteInitParameters struct {

	// (Boolean) Allow admin console access through this route. Defaults to false.
	// Allow admin console access through this route. Defaults to `false`.
	AllowAdminAccess *bool `json:"allowAdminAccess,omitempty" tf:"allow_admin_access,omitempty"`

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/cluster/skycloak/v1alpha1.Cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (List of String) CORS allowed origins for this route.
	// CORS allowed origins for this route.
	CorsAllowedOrigins []*string `json:"corsAllowedOrigins,omitempty" tf:"cors_allowed_origins,omitempty"`

	// (String) Custom domain ID. Immutable.
	// Custom domain ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/cluster/skycloak/v1alpha1.Domain
	DomainID *string `json:"domainId,omitempty" tf:"domain_id,omitempty"`

	// Reference to a Domain in skycloak to populate domainId.
	// +kubebuilder:validation:Optional
	DomainIDRef *v2.Reference `json:"domainIdRef,omitempty" tf:"-"`

	// Selector for a Domain in skycloak to populate domainId.
	// +kubebuilder:validation:Optional
	DomainIDSelector *v2.Selector `json:"domainIdSelector,omitempty" tf:"-"`

	// (Boolean) Serve the realm at the domain root (hide /realms/<name>). Set at creation; immutable.
	// Serve the realm at the domain root (hide `/realms/<name>`). Set at creation; immutable.
	HideRealmPath *bool `json:"hideRealmPath,omitempty" tf:"hide_realm_path,omitempty"`

	// (String) Realm to route. Immutable.
	// Realm to route. Immutable.
	Realm *string `json:"realm,omitempty" tf:"realm,omitempty"`
}

type DomainRouteObservation struct {

	// (Boolean) Allow admin console access through this route. Defaults to false.
	// Allow admin console access through this route. Defaults to `false`.
	AllowAdminAccess *bool `json:"allowAdminAccess,omitempty" tf:"allow_admin_access,omitempty"`

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (List of String) CORS allowed origins for this route.
	// CORS allowed origins for this route.
	CorsAllowedOrigins []*string `json:"corsAllowedOrigins,omitempty" tf:"cors_allowed_origins,omitempty"`

	// (String)
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) Custom domain ID. Immutable.
	// Custom domain ID. Immutable.
	DomainID *string `json:"domainId,omitempty" tf:"domain_id,omitempty"`

	// (Boolean) Serve the realm at the domain root (hide /realms/<name>). Set at creation; immutable.
	// Serve the realm at the domain root (hide `/realms/<name>`). Set at creation; immutable.
	HideRealmPath *bool `json:"hideRealmPath,omitempty" tf:"hide_realm_path,omitempty"`

	// (String) Route ID (UUID).
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Realm to route. Immutable.
	// Realm to route. Immutable.
	Realm *string `json:"realm,omitempty" tf:"realm,omitempty"`

	// (String)
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type DomainRouteParameters struct {

	// (Boolean) Allow admin console access through this route. Defaults to false.
	// Allow admin console access through this route. Defaults to `false`.
	// +kubebuilder:validation:Optional
	AllowAdminAccess *bool `json:"allowAdminAccess,omitempty" tf:"allow_admin_access,omitempty"`

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/cluster/skycloak/v1alpha1.Cluster
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (List of String) CORS allowed origins for this route.
	// CORS allowed origins for this route.
	// +kubebuilder:validation:Optional
	CorsAllowedOrigins []*string `json:"corsAllowedOrigins,omitempty" tf:"cors_allowed_origins,omitempty"`

	// (String) Custom domain ID. Immutable.
	// Custom domain ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/cluster/skycloak/v1alpha1.Domain
	// +kubebuilder:validation:Optional
	DomainID *string `json:"domainId,omitempty" tf:"domain_id,omitempty"`

	// Reference to a Domain in skycloak to populate domainId.
	// +kubebuilder:validation:Optional
	DomainIDRef *v2.Reference `json:"domainIdRef,omitempty" tf:"-"`

	// Selector for a Domain in skycloak to populate domainId.
	// +kubebuilder:validation:Optional
	DomainIDSelector *v2.Selector `json:"domainIdSelector,omitempty" tf:"-"`

	// (Boolean) Serve the realm at the domain root (hide /realms/<name>). Set at creation; immutable.
	// Serve the realm at the domain root (hide `/realms/<name>`). Set at creation; immutable.
	// +kubebuilder:validation:Optional
	HideRealmPath *bool `json:"hideRealmPath,omitempty" tf:"hide_realm_path,omitempty"`

	// (String) Realm to route. Immutable.
	// Realm to route. Immutable.
	// +kubebuilder:validation:Optional
	Realm *string `json:"realm,omitempty" tf:"realm,omitempty"`
}

// DomainRouteSpec defines the desired state of DomainRoute
type DomainRouteSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   DomainRouteParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DomainRouteInitParameters `json:"initProvider,omitempty"`
}

// DomainRouteStatus defines the observed state of DomainRoute.
type DomainRouteStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               DomainRouteObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DomainRoute is the Schema for the DomainRoutes API. Maps a realm onto a custom domain.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,skycloak}
type DomainRoute struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.realm) || (has(self.initProvider) && has(self.initProvider.realm))",message="spec.forProvider.realm is a required parameter"
	Spec   DomainRouteSpec   `json:"spec"`
	Status DomainRouteStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DomainRouteList contains a list of DomainRoutes
type DomainRouteList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DomainRoute `json:"items"`
}

// Repository type metadata.
var (
	DomainRoute_Kind             = "DomainRoute"
	DomainRoute_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DomainRoute_Kind}.String()
	DomainRoute_KindAPIVersion   = DomainRoute_Kind + "." + CRDGroupVersion.String()
	DomainRoute_GroupVersionKind = CRDGroupVersion.WithKind(DomainRoute_Kind)
)

func init() {
	SchemeBuilder.Register(&DomainRoute{}, &DomainRouteList{})
}
