/*
Copyright 2026 Decade Engineering
*/

// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ExportInitParameters struct {

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/cluster/skycloak/v1alpha1.Cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// 256-CBC). Required when include_credentials is true. Write-only; never read back. Immutable.
	// Password used to encrypt the archive (AES-256-CBC). Required when `include_credentials` is true. Write-only; never read back. Immutable.
	EncryptionPasswordSecretRef *v2.SecretKeySelector `json:"encryptionPasswordSecretRef,omitempty" tf:"-"`

	// (String) Export format: pgdump or sql. Immutable.
	// Export format: `pgdump` or `sql`. Immutable.
	Format *string `json:"format,omitempty" tf:"format,omitempty"`

	// (Boolean) Include the Keycloak credential and related tables. Requires encryption_password. Immutable.
	// Include the Keycloak `credential` and related tables. Requires `encryption_password`. Immutable.
	IncludeCredentials *bool `json:"includeCredentials,omitempty" tf:"include_credentials,omitempty"`
}

type ExportObservation struct {

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (String) Completion timestamp (RFC 3339).
	// Completion timestamp (RFC 3339).
	CompletedAt *string `json:"completedAt,omitempty" tf:"completed_at,omitempty"`

	// (String) Creation timestamp (RFC 3339).
	// Creation timestamp (RFC 3339).
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) When the archive is deleted from storage (RFC 3339).
	// When the archive is deleted from storage (RFC 3339).
	ExpiresAt *string `json:"expiresAt,omitempty" tf:"expires_at,omitempty"`

	// (Number) Size of the produced archive in bytes.
	// Size of the produced archive in bytes.
	FileSizeBytes *float64 `json:"fileSizeBytes,omitempty" tf:"file_size_bytes,omitempty"`

	// (String) Export format: pgdump or sql. Immutable.
	// Export format: `pgdump` or `sql`. Immutable.
	Format *string `json:"format,omitempty" tf:"format,omitempty"`

	// (String) Export job ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Include the Keycloak credential and related tables. Requires encryption_password. Immutable.
	// Include the Keycloak `credential` and related tables. Requires `encryption_password`. Immutable.
	IncludeCredentials *bool `json:"includeCredentials,omitempty" tf:"include_credentials,omitempty"`

	// (Boolean) Whether the archive is encrypted.
	// Whether the archive is encrypted.
	IsEncrypted *bool `json:"isEncrypted,omitempty" tf:"is_encrypted,omitempty"`

	// 100).
	// Completion percentage (0-100).
	Progress *float64 `json:"progress,omitempty" tf:"progress,omitempty"`

	// 256 checksum of the archive (hex).
	// SHA-256 checksum of the archive (hex).
	Sha256Checksum *string `json:"sha256Checksum,omitempty" tf:"sha256_checksum,omitempty"`

	// (String) Job status (pending, processing, completed, failed).
	// Job status (`pending`, `processing`, `completed`, `failed`).
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type ExportParameters struct {

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/cluster/skycloak/v1alpha1.Cluster
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// 256-CBC). Required when include_credentials is true. Write-only; never read back. Immutable.
	// Password used to encrypt the archive (AES-256-CBC). Required when `include_credentials` is true. Write-only; never read back. Immutable.
	// +kubebuilder:validation:Optional
	EncryptionPasswordSecretRef *v2.SecretKeySelector `json:"encryptionPasswordSecretRef,omitempty" tf:"-"`

	// (String) Export format: pgdump or sql. Immutable.
	// Export format: `pgdump` or `sql`. Immutable.
	// +kubebuilder:validation:Optional
	Format *string `json:"format,omitempty" tf:"format,omitempty"`

	// (Boolean) Include the Keycloak credential and related tables. Requires encryption_password. Immutable.
	// Include the Keycloak `credential` and related tables. Requires `encryption_password`. Immutable.
	// +kubebuilder:validation:Optional
	IncludeCredentials *bool `json:"includeCredentials,omitempty" tf:"include_credentials,omitempty"`
}

// ExportSpec defines the desired state of Export
type ExportSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   ExportParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ExportInitParameters `json:"initProvider,omitempty"`
}

// ExportStatus defines the observed state of Export.
type ExportStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ExportObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Export is the Schema for the Exports API. A one-shot database export job for a cluster. Creating the resource starts the export and waits for it to finish. The archive expires; recreate the resource to produce a fresh export.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,skycloak}
type Export struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.format) || (has(self.initProvider) && has(self.initProvider.format))",message="spec.forProvider.format is a required parameter"
	Spec   ExportSpec   `json:"spec"`
	Status ExportStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ExportList contains a list of Exports
type ExportList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Export `json:"items"`
}

// Repository type metadata.
var (
	Export_Kind             = "Export"
	Export_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Export_Kind}.String()
	Export_KindAPIVersion   = Export_Kind + "." + CRDGroupVersion.String()
	Export_GroupVersionKind = CRDGroupVersion.WithKind(Export_Kind)
)

func init() {
	SchemeBuilder.Register(&Export{}, &ExportList{})
}
