/*
Copyright 2026 Decade Engineering
*/

// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Application) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ApplicationRoleAssignment) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ApplicationSecret) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CaptchaDomain) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ClientThemeAssignment) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Cluster) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ClusterExtension) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ClusterMaintenanceWindow) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ClusterSecurity) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CustomExtension) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CustomTheme) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Domain) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DomainRoute) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *EmailBranding) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Export) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *IdentityProvider) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LoginBranding) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Realm) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RealmExport) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RealmGroup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RealmGroupMembership) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RealmImport) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RealmRole) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RealmUser) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RealmUserRoleAssignment) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SIEMDestination) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SMTP) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ThemeAssignment) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *WebhookSubscription) Hub() {}
