/*
Copyright 2026 Decade Engineering
*/

// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type LoginBrandingInitParameters struct {

	// (String) Login page background color (hex).
	// Login page background color (hex).
	BackgroundColor *string `json:"backgroundColor,omitempty" tf:"background_color,omitempty"`

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/cluster/skycloak/v1alpha1.Cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (String) URL of the browser favicon.
	// URL of the browser favicon.
	FaviconURL *string `json:"faviconUrl,omitempty" tf:"favicon_url,omitempty"`

	// (String) URL of a custom web font.
	// URL of a custom web font.
	FontURL *string `json:"fontUrl,omitempty" tf:"font_url,omitempty"`

	// (Boolean) Defaults to the API's value when unset.
	// Defaults to the API's value when unset.
	ForgotPasswordEnabled *bool `json:"forgotPasswordEnabled,omitempty" tf:"forgot_password_enabled,omitempty"`

	// (Attributes) Login page internationalization settings. (see below for nested schema)
	Internationalization *LoginBrandingInternationalizationInitParameters `json:"internationalization,omitempty" tf:"internationalization,omitempty"`

	// (String) URL of the logo displayed on the login page.
	// URL of the logo displayed on the login page.
	LogoURL *string `json:"logoUrl,omitempty" tf:"logo_url,omitempty"`

	// (String) Primary accent color applied to buttons (hex, e.g. #0ea5e9).
	// Primary accent color applied to buttons (hex, e.g. `#0ea5e9`).
	PrimaryColor *string `json:"primaryColor,omitempty" tf:"primary_color,omitempty"`

	// (String) URL of the privacy policy linked in the footer.
	// URL of the privacy policy linked in the footer.
	PrivacyPolicyURL *string `json:"privacyPolicyUrl,omitempty" tf:"privacy_policy_url,omitempty"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`

	// (Boolean) Defaults to the API's value when unset.
	// Defaults to the API's value when unset.
	RegistrationEnabled *bool `json:"registrationEnabled,omitempty" tf:"registration_enabled,omitempty"`

	// (Boolean) Defaults to the API's value when unset.
	// Defaults to the API's value when unset.
	RememberMeEnabled *bool `json:"rememberMeEnabled,omitempty" tf:"remember_me_enabled,omitempty"`

	// (Boolean) Defaults to the API's value when unset.
	// Defaults to the API's value when unset.
	ShowPoweredBy *bool `json:"showPoweredBy,omitempty" tf:"show_powered_by,omitempty"`

	// provider button display on the login page. (see below for nested schema)
	Sso *SsoInitParameters `json:"sso,omitempty" tf:"sso,omitempty"`

	// (String) URL of the terms of service linked in the footer.
	// URL of the terms of service linked in the footer.
	TermsOfServiceURL *string `json:"termsOfServiceUrl,omitempty" tf:"terms_of_service_url,omitempty"`
}

type LoginBrandingInternationalizationInitParameters struct {

	// (String) Default locale (BCP 47 tag, e.g. en).
	// Default locale (BCP 47 tag, e.g. `en`).
	DefaultLocale *string `json:"defaultLocale,omitempty" tf:"default_locale,omitempty"`

	// (Boolean) Whether internationalization is enabled.
	// Whether internationalization is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) automatic_only, automatic_with_selector, hide_selector, or selector_only.
	// `automatic_only`, `automatic_with_selector`, `hide_selector`, or `selector_only`.
	LanguageSelectionMode *string `json:"languageSelectionMode,omitempty" tf:"language_selection_mode,omitempty"`

	// (String) form_inside_header, form_inside_left, top_left, top_middle, or top_right.
	// `form_inside_header`, `form_inside_left`, `top_left`, `top_middle`, or `top_right`.
	LanguageSelectorPosition *string `json:"languageSelectorPosition,omitempty" tf:"language_selector_position,omitempty"`

	// (String) dropdown, flags, or text_labels.
	// `dropdown`, `flags`, or `text_labels`.
	LanguageSelectorStyle *string `json:"languageSelectorStyle,omitempty" tf:"language_selector_style,omitempty"`

	// (List of String) Locales available to users. Must include default_locale.
	// Locales available to users. Must include `default_locale`.
	SupportedLocales []*string `json:"supportedLocales,omitempty" tf:"supported_locales,omitempty"`
}

type LoginBrandingInternationalizationObservation struct {

	// (String) Default locale (BCP 47 tag, e.g. en).
	// Default locale (BCP 47 tag, e.g. `en`).
	DefaultLocale *string `json:"defaultLocale,omitempty" tf:"default_locale,omitempty"`

	// (Boolean) Whether internationalization is enabled.
	// Whether internationalization is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) automatic_only, automatic_with_selector, hide_selector, or selector_only.
	// `automatic_only`, `automatic_with_selector`, `hide_selector`, or `selector_only`.
	LanguageSelectionMode *string `json:"languageSelectionMode,omitempty" tf:"language_selection_mode,omitempty"`

	// (String) form_inside_header, form_inside_left, top_left, top_middle, or top_right.
	// `form_inside_header`, `form_inside_left`, `top_left`, `top_middle`, or `top_right`.
	LanguageSelectorPosition *string `json:"languageSelectorPosition,omitempty" tf:"language_selector_position,omitempty"`

	// (String) dropdown, flags, or text_labels.
	// `dropdown`, `flags`, or `text_labels`.
	LanguageSelectorStyle *string `json:"languageSelectorStyle,omitempty" tf:"language_selector_style,omitempty"`

	// (List of String) Locales available to users. Must include default_locale.
	// Locales available to users. Must include `default_locale`.
	SupportedLocales []*string `json:"supportedLocales,omitempty" tf:"supported_locales,omitempty"`
}

type LoginBrandingInternationalizationParameters struct {

	// (String) Default locale (BCP 47 tag, e.g. en).
	// Default locale (BCP 47 tag, e.g. `en`).
	// +kubebuilder:validation:Optional
	DefaultLocale *string `json:"defaultLocale" tf:"default_locale,omitempty"`

	// (Boolean) Whether internationalization is enabled.
	// Whether internationalization is enabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled" tf:"enabled,omitempty"`

	// (String) automatic_only, automatic_with_selector, hide_selector, or selector_only.
	// `automatic_only`, `automatic_with_selector`, `hide_selector`, or `selector_only`.
	// +kubebuilder:validation:Optional
	LanguageSelectionMode *string `json:"languageSelectionMode" tf:"language_selection_mode,omitempty"`

	// (String) form_inside_header, form_inside_left, top_left, top_middle, or top_right.
	// `form_inside_header`, `form_inside_left`, `top_left`, `top_middle`, or `top_right`.
	// +kubebuilder:validation:Optional
	LanguageSelectorPosition *string `json:"languageSelectorPosition" tf:"language_selector_position,omitempty"`

	// (String) dropdown, flags, or text_labels.
	// `dropdown`, `flags`, or `text_labels`.
	// +kubebuilder:validation:Optional
	LanguageSelectorStyle *string `json:"languageSelectorStyle" tf:"language_selector_style,omitempty"`

	// (List of String) Locales available to users. Must include default_locale.
	// Locales available to users. Must include `default_locale`.
	// +kubebuilder:validation:Optional
	SupportedLocales []*string `json:"supportedLocales" tf:"supported_locales,omitempty"`
}

type LoginBrandingObservation struct {

	// (String) Login page background color (hex).
	// Login page background color (hex).
	BackgroundColor *string `json:"backgroundColor,omitempty" tf:"background_color,omitempty"`

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (String) URL of the browser favicon.
	// URL of the browser favicon.
	FaviconURL *string `json:"faviconUrl,omitempty" tf:"favicon_url,omitempty"`

	// (String) URL of a custom web font.
	// URL of a custom web font.
	FontURL *string `json:"fontUrl,omitempty" tf:"font_url,omitempty"`

	// (Boolean) Defaults to the API's value when unset.
	// Defaults to the API's value when unset.
	ForgotPasswordEnabled *bool `json:"forgotPasswordEnabled,omitempty" tf:"forgot_password_enabled,omitempty"`

	// (String) Composite ID cluster_id/realm_name/login_branding.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Attributes) Login page internationalization settings. (see below for nested schema)
	Internationalization *LoginBrandingInternationalizationObservation `json:"internationalization,omitempty" tf:"internationalization,omitempty"`

	// (String) URL of the logo displayed on the login page.
	// URL of the logo displayed on the login page.
	LogoURL *string `json:"logoUrl,omitempty" tf:"logo_url,omitempty"`

	// (String) Primary accent color applied to buttons (hex, e.g. #0ea5e9).
	// Primary accent color applied to buttons (hex, e.g. `#0ea5e9`).
	PrimaryColor *string `json:"primaryColor,omitempty" tf:"primary_color,omitempty"`

	// (String) URL of the privacy policy linked in the footer.
	// URL of the privacy policy linked in the footer.
	PrivacyPolicyURL *string `json:"privacyPolicyUrl,omitempty" tf:"privacy_policy_url,omitempty"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`

	// (Boolean) Defaults to the API's value when unset.
	// Defaults to the API's value when unset.
	RegistrationEnabled *bool `json:"registrationEnabled,omitempty" tf:"registration_enabled,omitempty"`

	// (Boolean) Defaults to the API's value when unset.
	// Defaults to the API's value when unset.
	RememberMeEnabled *bool `json:"rememberMeEnabled,omitempty" tf:"remember_me_enabled,omitempty"`

	// (Boolean) Defaults to the API's value when unset.
	// Defaults to the API's value when unset.
	ShowPoweredBy *bool `json:"showPoweredBy,omitempty" tf:"show_powered_by,omitempty"`

	// provider button display on the login page. (see below for nested schema)
	Sso *SsoObservation `json:"sso,omitempty" tf:"sso,omitempty"`

	// (String) Deployment status (applied, applying, failed).
	// Deployment status (`applied`, `applying`, `failed`).
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (String) URL of the terms of service linked in the footer.
	// URL of the terms of service linked in the footer.
	TermsOfServiceURL *string `json:"termsOfServiceUrl,omitempty" tf:"terms_of_service_url,omitempty"`
}

type LoginBrandingParameters struct {

	// (String) Login page background color (hex).
	// Login page background color (hex).
	// +kubebuilder:validation:Optional
	BackgroundColor *string `json:"backgroundColor,omitempty" tf:"background_color,omitempty"`

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/cluster/skycloak/v1alpha1.Cluster
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (String) URL of the browser favicon.
	// URL of the browser favicon.
	// +kubebuilder:validation:Optional
	FaviconURL *string `json:"faviconUrl,omitempty" tf:"favicon_url,omitempty"`

	// (String) URL of a custom web font.
	// URL of a custom web font.
	// +kubebuilder:validation:Optional
	FontURL *string `json:"fontUrl,omitempty" tf:"font_url,omitempty"`

	// (Boolean) Defaults to the API's value when unset.
	// Defaults to the API's value when unset.
	// +kubebuilder:validation:Optional
	ForgotPasswordEnabled *bool `json:"forgotPasswordEnabled,omitempty" tf:"forgot_password_enabled,omitempty"`

	// (Attributes) Login page internationalization settings. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Internationalization *LoginBrandingInternationalizationParameters `json:"internationalization,omitempty" tf:"internationalization,omitempty"`

	// (String) URL of the logo displayed on the login page.
	// URL of the logo displayed on the login page.
	// +kubebuilder:validation:Optional
	LogoURL *string `json:"logoUrl,omitempty" tf:"logo_url,omitempty"`

	// (String) Primary accent color applied to buttons (hex, e.g. #0ea5e9).
	// Primary accent color applied to buttons (hex, e.g. `#0ea5e9`).
	// +kubebuilder:validation:Optional
	PrimaryColor *string `json:"primaryColor,omitempty" tf:"primary_color,omitempty"`

	// (String) URL of the privacy policy linked in the footer.
	// URL of the privacy policy linked in the footer.
	// +kubebuilder:validation:Optional
	PrivacyPolicyURL *string `json:"privacyPolicyUrl,omitempty" tf:"privacy_policy_url,omitempty"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	// +kubebuilder:validation:Optional
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`

	// (Boolean) Defaults to the API's value when unset.
	// Defaults to the API's value when unset.
	// +kubebuilder:validation:Optional
	RegistrationEnabled *bool `json:"registrationEnabled,omitempty" tf:"registration_enabled,omitempty"`

	// (Boolean) Defaults to the API's value when unset.
	// Defaults to the API's value when unset.
	// +kubebuilder:validation:Optional
	RememberMeEnabled *bool `json:"rememberMeEnabled,omitempty" tf:"remember_me_enabled,omitempty"`

	// (Boolean) Defaults to the API's value when unset.
	// Defaults to the API's value when unset.
	// +kubebuilder:validation:Optional
	ShowPoweredBy *bool `json:"showPoweredBy,omitempty" tf:"show_powered_by,omitempty"`

	// provider button display on the login page. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Sso *SsoParameters `json:"sso,omitempty" tf:"sso,omitempty"`

	// (String) URL of the terms of service linked in the footer.
	// URL of the terms of service linked in the footer.
	// +kubebuilder:validation:Optional
	TermsOfServiceURL *string `json:"termsOfServiceUrl,omitempty" tf:"terms_of_service_url,omitempty"`
}

type SsoInitParameters struct {

	// (String) small, medium, or large.
	// `small`, `medium`, or `large`.
	ButtonSize *string `json:"buttonSize,omitempty" tf:"button_size,omitempty"`

	// (String) logo_only, logo_with_text, or text_only.
	// `logo_only`, `logo_with_text`, or `text_only`.
	DisplayStyle *string `json:"displayStyle,omitempty" tf:"display_style,omitempty"`

	// (Boolean) Whether internationalization is enabled.
	// Show identity provider buttons on the login page.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) horizontal or vertical.
	// `horizontal` or `vertical`.
	Layout *string `json:"layout,omitempty" tf:"layout,omitempty"`
}

type SsoObservation struct {

	// (String) small, medium, or large.
	// `small`, `medium`, or `large`.
	ButtonSize *string `json:"buttonSize,omitempty" tf:"button_size,omitempty"`

	// (String) logo_only, logo_with_text, or text_only.
	// `logo_only`, `logo_with_text`, or `text_only`.
	DisplayStyle *string `json:"displayStyle,omitempty" tf:"display_style,omitempty"`

	// (Boolean) Whether internationalization is enabled.
	// Show identity provider buttons on the login page.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) horizontal or vertical.
	// `horizontal` or `vertical`.
	Layout *string `json:"layout,omitempty" tf:"layout,omitempty"`
}

type SsoParameters struct {

	// (String) small, medium, or large.
	// `small`, `medium`, or `large`.
	// +kubebuilder:validation:Optional
	ButtonSize *string `json:"buttonSize" tf:"button_size,omitempty"`

	// (String) logo_only, logo_with_text, or text_only.
	// `logo_only`, `logo_with_text`, or `text_only`.
	// +kubebuilder:validation:Optional
	DisplayStyle *string `json:"displayStyle" tf:"display_style,omitempty"`

	// (Boolean) Whether internationalization is enabled.
	// Show identity provider buttons on the login page.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled" tf:"enabled,omitempty"`

	// (String) horizontal or vertical.
	// `horizontal` or `vertical`.
	// +kubebuilder:validation:Optional
	Layout *string `json:"layout" tf:"layout,omitempty"`
}

// LoginBrandingSpec defines the desired state of LoginBranding
type LoginBrandingSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   LoginBrandingParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider LoginBrandingInitParameters `json:"initProvider,omitempty"`
}

// LoginBrandingStatus defines the observed state of LoginBranding.
type LoginBrandingStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               LoginBrandingObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// LoginBranding is the Schema for the LoginBrandings API. Login-page branding for a realm (a singleton; create == update upsert).
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,skycloak}
type LoginBranding struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.realmName) || (has(self.initProvider) && has(self.initProvider.realmName))",message="spec.forProvider.realmName is a required parameter"
	Spec   LoginBrandingSpec   `json:"spec"`
	Status LoginBrandingStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// LoginBrandingList contains a list of LoginBrandings
type LoginBrandingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []LoginBranding `json:"items"`
}

// Repository type metadata.
var (
	LoginBranding_Kind             = "LoginBranding"
	LoginBranding_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: LoginBranding_Kind}.String()
	LoginBranding_KindAPIVersion   = LoginBranding_Kind + "." + CRDGroupVersion.String()
	LoginBranding_GroupVersionKind = CRDGroupVersion.WithKind(LoginBranding_Kind)
)

func init() {
	SchemeBuilder.Register(&LoginBranding{}, &LoginBrandingList{})
}
