/*
Copyright 2026 Decade Engineering
*/

// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type RealmUserInitParameters struct {

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/cluster/skycloak/v1alpha1.Cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (String) Email address.
	// Email address.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// (Boolean) Whether the email address is verified. Defaults to false.
	// Whether the email address is verified. Defaults to `false`.
	EmailVerified *bool `json:"emailVerified,omitempty" tf:"email_verified,omitempty"`

	// (Boolean) Whether the user can sign in. Defaults to true.
	// Whether the user can sign in. Defaults to `true`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) First name.
	// First name.
	FirstName *string `json:"firstName,omitempty" tf:"first_name,omitempty"`

	// (String) Last name.
	// Last name.
	LastName *string `json:"lastName,omitempty" tf:"last_name,omitempty"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`

	// only; changing it recreates the user (there is no password-update endpoint).
	// Initial password (min 8 chars). Write-only; changing it recreates the user (there is no password-update endpoint).
	TemporaryPasswordSecretRef v2.SecretKeySelector `json:"temporaryPasswordSecretRef" tf:"-"`

	// (String) Username. Immutable.
	// Username. Immutable.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type RealmUserObservation struct {

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (String) Creation timestamp (RFC 3339).
	// Creation timestamp (RFC 3339).
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) Email address.
	// Email address.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// (Boolean) Whether the email address is verified. Defaults to false.
	// Whether the email address is verified. Defaults to `false`.
	EmailVerified *bool `json:"emailVerified,omitempty" tf:"email_verified,omitempty"`

	// (Boolean) Whether the user can sign in. Defaults to true.
	// Whether the user can sign in. Defaults to `true`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) First name.
	// First name.
	FirstName *string `json:"firstName,omitempty" tf:"first_name,omitempty"`

	// (String) User ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// in (RFC 3339).
	// Most recent sign-in (RFC 3339).
	LastLoginAt *string `json:"lastLoginAt,omitempty" tf:"last_login_at,omitempty"`

	// (String) Last name.
	// Last name.
	LastName *string `json:"lastName,omitempty" tf:"last_name,omitempty"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`

	// (String) Username. Immutable.
	// Username. Immutable.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type RealmUserParameters struct {

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/cluster/skycloak/v1alpha1.Cluster
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (String) Email address.
	// Email address.
	// +kubebuilder:validation:Optional
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// (Boolean) Whether the email address is verified. Defaults to false.
	// Whether the email address is verified. Defaults to `false`.
	// +kubebuilder:validation:Optional
	EmailVerified *bool `json:"emailVerified,omitempty" tf:"email_verified,omitempty"`

	// (Boolean) Whether the user can sign in. Defaults to true.
	// Whether the user can sign in. Defaults to `true`.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) First name.
	// First name.
	// +kubebuilder:validation:Optional
	FirstName *string `json:"firstName,omitempty" tf:"first_name,omitempty"`

	// (String) Last name.
	// Last name.
	// +kubebuilder:validation:Optional
	LastName *string `json:"lastName,omitempty" tf:"last_name,omitempty"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	// +kubebuilder:validation:Optional
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`

	// only; changing it recreates the user (there is no password-update endpoint).
	// Initial password (min 8 chars). Write-only; changing it recreates the user (there is no password-update endpoint).
	// +kubebuilder:validation:Optional
	TemporaryPasswordSecretRef v2.SecretKeySelector `json:"temporaryPasswordSecretRef" tf:"-"`

	// (String) Username. Immutable.
	// Username. Immutable.
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

// RealmUserSpec defines the desired state of RealmUser
type RealmUserSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   RealmUserParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RealmUserInitParameters `json:"initProvider,omitempty"`
}

// RealmUserStatus defines the observed state of RealmUser.
type RealmUserStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               RealmUserObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RealmUser is the Schema for the RealmUsers API. A realm user. Grant roles with skycloak_realm_user_role_assignment and group membership with skycloak_realm_group_membership.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,skycloak}
type RealmUser struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.email) || (has(self.initProvider) && has(self.initProvider.email))",message="spec.forProvider.email is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.realmName) || (has(self.initProvider) && has(self.initProvider.realmName))",message="spec.forProvider.realmName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.temporaryPasswordSecretRef)",message="spec.forProvider.temporaryPasswordSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.username) || (has(self.initProvider) && has(self.initProvider.username))",message="spec.forProvider.username is a required parameter"
	Spec   RealmUserSpec   `json:"spec"`
	Status RealmUserStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RealmUserList contains a list of RealmUsers
type RealmUserList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RealmUser `json:"items"`
}

// Repository type metadata.
var (
	RealmUser_Kind             = "RealmUser"
	RealmUser_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RealmUser_Kind}.String()
	RealmUser_KindAPIVersion   = RealmUser_Kind + "." + CRDGroupVersion.String()
	RealmUser_GroupVersionKind = CRDGroupVersion.WithKind(RealmUser_Kind)
)

func init() {
	SchemeBuilder.Register(&RealmUser{}, &RealmUserList{})
}
