/*
Copyright 2026 Decade Engineering
*/

// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type RealmUserRoleAssignmentInitParameters struct {

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/cluster/skycloak/v1alpha1.Cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`

	// (String) Realm role name. Immutable.
	// Realm role name. Immutable.
	RoleName *string `json:"roleName,omitempty" tf:"role_name,omitempty"`

	// (String) User ID. Immutable.
	// User ID. Immutable.
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type RealmUserRoleAssignmentObservation struct {

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`

	// (String) Realm role name. Immutable.
	// Realm role name. Immutable.
	RoleName *string `json:"roleName,omitempty" tf:"role_name,omitempty"`

	// (String) User ID. Immutable.
	// User ID. Immutable.
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type RealmUserRoleAssignmentParameters struct {

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/cluster/skycloak/v1alpha1.Cluster
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	// +kubebuilder:validation:Optional
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`

	// (String) Realm role name. Immutable.
	// Realm role name. Immutable.
	// +kubebuilder:validation:Optional
	RoleName *string `json:"roleName,omitempty" tf:"role_name,omitempty"`

	// (String) User ID. Immutable.
	// User ID. Immutable.
	// +kubebuilder:validation:Optional
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

// RealmUserRoleAssignmentSpec defines the desired state of RealmUserRoleAssignment
type RealmUserRoleAssignmentSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   RealmUserRoleAssignmentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RealmUserRoleAssignmentInitParameters `json:"initProvider,omitempty"`
}

// RealmUserRoleAssignmentStatus defines the observed state of RealmUserRoleAssignment.
type RealmUserRoleAssignmentStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               RealmUserRoleAssignmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RealmUserRoleAssignment is the Schema for the RealmUserRoleAssignments API. Assigns a single realm role to a user. One resource per (user, role) edge.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,skycloak}
type RealmUserRoleAssignment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.realmName) || (has(self.initProvider) && has(self.initProvider.realmName))",message="spec.forProvider.realmName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.roleName) || (has(self.initProvider) && has(self.initProvider.roleName))",message="spec.forProvider.roleName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.userId) || (has(self.initProvider) && has(self.initProvider.userId))",message="spec.forProvider.userId is a required parameter"
	Spec   RealmUserRoleAssignmentSpec   `json:"spec"`
	Status RealmUserRoleAssignmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RealmUserRoleAssignmentList contains a list of RealmUserRoleAssignments
type RealmUserRoleAssignmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RealmUserRoleAssignment `json:"items"`
}

// Repository type metadata.
var (
	RealmUserRoleAssignment_Kind             = "RealmUserRoleAssignment"
	RealmUserRoleAssignment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RealmUserRoleAssignment_Kind}.String()
	RealmUserRoleAssignment_KindAPIVersion   = RealmUserRoleAssignment_Kind + "." + CRDGroupVersion.String()
	RealmUserRoleAssignment_GroupVersionKind = CRDGroupVersion.WithKind(RealmUserRoleAssignment_Kind)
)

func init() {
	SchemeBuilder.Register(&RealmUserRoleAssignment{}, &RealmUserRoleAssignmentList{})
}
