/*
Copyright 2026 Decade Engineering
*/

// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type RealmGroupInitParameters struct {

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/cluster/skycloak/v1alpha1.Cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (String) Group name (leaf segment of the path).
	// Group name (leaf segment of the path).
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Parent group ID for a nested group. Immutable.
	// Parent group ID for a nested group. Immutable.
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`
}

type RealmGroupObservation struct {

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (String) Group ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Group name (leaf segment of the path).
	// Group name (leaf segment of the path).
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Parent group ID for a nested group. Immutable.
	// Parent group ID for a nested group. Immutable.
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// (String) Canonical group path.
	// Canonical group path.
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`
}

type RealmGroupParameters struct {

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/cluster/skycloak/v1alpha1.Cluster
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (String) Group name (leaf segment of the path).
	// Group name (leaf segment of the path).
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Parent group ID for a nested group. Immutable.
	// Parent group ID for a nested group. Immutable.
	// +kubebuilder:validation:Optional
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	// +kubebuilder:validation:Optional
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`
}

// RealmGroupSpec defines the desired state of RealmGroup
type RealmGroupSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   RealmGroupParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RealmGroupInitParameters `json:"initProvider,omitempty"`
}

// RealmGroupStatus defines the observed state of RealmGroup.
type RealmGroupStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               RealmGroupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RealmGroup is the Schema for the RealmGroups API. A realm group. Add users with skycloak_realm_group_membership.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,skycloak}
type RealmGroup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.realmName) || (has(self.initProvider) && has(self.initProvider.realmName))",message="spec.forProvider.realmName is a required parameter"
	Spec   RealmGroupSpec   `json:"spec"`
	Status RealmGroupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RealmGroupList contains a list of RealmGroups
type RealmGroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RealmGroup `json:"items"`
}

// Repository type metadata.
var (
	RealmGroup_Kind             = "RealmGroup"
	RealmGroup_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RealmGroup_Kind}.String()
	RealmGroup_KindAPIVersion   = RealmGroup_Kind + "." + CRDGroupVersion.String()
	RealmGroup_GroupVersionKind = CRDGroupVersion.WithKind(RealmGroup_Kind)
)

func init() {
	SchemeBuilder.Register(&RealmGroup{}, &RealmGroupList{})
}
