/*
Copyright 2026 Decade Engineering
*/

// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type SMTPInitParameters struct {

	// (String) Authentication type: basic or oauth2.
	// Authentication type: `basic` or `oauth2`.
	AuthType *string `json:"authType,omitempty" tf:"auth_type,omitempty"`

	// (String) OAuth 2.0 client ID (when auth_type is oauth2).
	// OAuth 2.0 client ID (when `auth_type` is `oauth2`).
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// only; never read back. Omit to retain the stored value.
	// OAuth 2.0 client secret. Write-only; never read back. Omit to retain the stored value.
	ClientSecretSecretRef *v2.SecretKeySelector `json:"clientSecretSecretRef,omitempty" tf:"-"`

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/cluster/skycloak/v1alpha1.Cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (String) Encryption mode: none, ssl, or starttls. Defaults to none.
	// Encryption mode: `none`, `ssl`, or `starttls`. Defaults to `none`.
	Encryption *string `json:"encryption,omitempty" tf:"encryption,omitempty"`

	// (String) Sender email address.
	// Sender email address.
	FromEmail *string `json:"fromEmail,omitempty" tf:"from_email,omitempty"`

	// (String) Sender display name.
	// Sender display name.
	FromName *string `json:"fromName,omitempty" tf:"from_name,omitempty"`

	// (String) SMTP server hostname or IP.
	// SMTP server hostname or IP.
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// only; never read back. Omit to retain the stored value.
	// SMTP password (when `auth_type` is `basic`). Write-only; never read back. Omit to retain the stored value.
	PasswordSecretRef *v2.SecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// 65535), e.g. 587.
	// SMTP server port (1-65535), e.g. 587.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`

	// (String) OAuth 2.0 token scope (when auth_type is oauth2).
	// OAuth 2.0 token scope (when `auth_type` is `oauth2`).
	TokenScope *string `json:"tokenScope,omitempty" tf:"token_scope,omitempty"`

	// (String) OAuth 2.0 token endpoint (when auth_type is oauth2).
	// OAuth 2.0 token endpoint (when `auth_type` is `oauth2`).
	TokenURL *string `json:"tokenUrl,omitempty" tf:"token_url,omitempty"`

	// (String) SMTP username (when auth_type is basic).
	// SMTP username (when `auth_type` is `basic`).
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type SMTPObservation struct {

	// (String) Authentication type: basic or oauth2.
	// Authentication type: `basic` or `oauth2`.
	AuthType *string `json:"authType,omitempty" tf:"auth_type,omitempty"`

	// (String) OAuth 2.0 client ID (when auth_type is oauth2).
	// OAuth 2.0 client ID (when `auth_type` is `oauth2`).
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (String) Encryption mode: none, ssl, or starttls. Defaults to none.
	// Encryption mode: `none`, `ssl`, or `starttls`. Defaults to `none`.
	Encryption *string `json:"encryption,omitempty" tf:"encryption,omitempty"`

	// (String) Sender email address.
	// Sender email address.
	FromEmail *string `json:"fromEmail,omitempty" tf:"from_email,omitempty"`

	// (String) Sender display name.
	// Sender display name.
	FromName *string `json:"fromName,omitempty" tf:"from_name,omitempty"`

	// (Boolean) Whether a client secret is stored.
	// Whether a client secret is stored.
	HasClientSecret *bool `json:"hasClientSecret,omitempty" tf:"has_client_secret,omitempty"`

	// (Boolean) Whether a password is stored.
	// Whether a password is stored.
	HasPassword *bool `json:"hasPassword,omitempty" tf:"has_password,omitempty"`

	// (String) SMTP server hostname or IP.
	// SMTP server hostname or IP.
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// (String) Composite ID cluster_id/realm_name/smtp.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// 65535), e.g. 587.
	// SMTP server port (1-65535), e.g. 587.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`

	// (String) Configuration status (configured, verified, failed).
	// Configuration status (`configured`, `verified`, `failed`).
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (String) OAuth 2.0 token scope (when auth_type is oauth2).
	// OAuth 2.0 token scope (when `auth_type` is `oauth2`).
	TokenScope *string `json:"tokenScope,omitempty" tf:"token_scope,omitempty"`

	// (String) OAuth 2.0 token endpoint (when auth_type is oauth2).
	// OAuth 2.0 token endpoint (when `auth_type` is `oauth2`).
	TokenURL *string `json:"tokenUrl,omitempty" tf:"token_url,omitempty"`

	// (String) SMTP username (when auth_type is basic).
	// SMTP username (when `auth_type` is `basic`).
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type SMTPParameters struct {

	// (String) Authentication type: basic or oauth2.
	// Authentication type: `basic` or `oauth2`.
	// +kubebuilder:validation:Optional
	AuthType *string `json:"authType,omitempty" tf:"auth_type,omitempty"`

	// (String) OAuth 2.0 client ID (when auth_type is oauth2).
	// OAuth 2.0 client ID (when `auth_type` is `oauth2`).
	// +kubebuilder:validation:Optional
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// only; never read back. Omit to retain the stored value.
	// OAuth 2.0 client secret. Write-only; never read back. Omit to retain the stored value.
	// +kubebuilder:validation:Optional
	ClientSecretSecretRef *v2.SecretKeySelector `json:"clientSecretSecretRef,omitempty" tf:"-"`

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/cluster/skycloak/v1alpha1.Cluster
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (String) Encryption mode: none, ssl, or starttls. Defaults to none.
	// Encryption mode: `none`, `ssl`, or `starttls`. Defaults to `none`.
	// +kubebuilder:validation:Optional
	Encryption *string `json:"encryption,omitempty" tf:"encryption,omitempty"`

	// (String) Sender email address.
	// Sender email address.
	// +kubebuilder:validation:Optional
	FromEmail *string `json:"fromEmail,omitempty" tf:"from_email,omitempty"`

	// (String) Sender display name.
	// Sender display name.
	// +kubebuilder:validation:Optional
	FromName *string `json:"fromName,omitempty" tf:"from_name,omitempty"`

	// (String) SMTP server hostname or IP.
	// SMTP server hostname or IP.
	// +kubebuilder:validation:Optional
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// only; never read back. Omit to retain the stored value.
	// SMTP password (when `auth_type` is `basic`). Write-only; never read back. Omit to retain the stored value.
	// +kubebuilder:validation:Optional
	PasswordSecretRef *v2.SecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// 65535), e.g. 587.
	// SMTP server port (1-65535), e.g. 587.
	// +kubebuilder:validation:Optional
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	// +kubebuilder:validation:Optional
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`

	// (String) OAuth 2.0 token scope (when auth_type is oauth2).
	// OAuth 2.0 token scope (when `auth_type` is `oauth2`).
	// +kubebuilder:validation:Optional
	TokenScope *string `json:"tokenScope,omitempty" tf:"token_scope,omitempty"`

	// (String) OAuth 2.0 token endpoint (when auth_type is oauth2).
	// OAuth 2.0 token endpoint (when `auth_type` is `oauth2`).
	// +kubebuilder:validation:Optional
	TokenURL *string `json:"tokenUrl,omitempty" tf:"token_url,omitempty"`

	// (String) SMTP username (when auth_type is basic).
	// SMTP username (when `auth_type` is `basic`).
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

// SMTPSpec defines the desired state of SMTP
type SMTPSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   SMTPParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SMTPInitParameters `json:"initProvider,omitempty"`
}

// SMTPStatus defines the observed state of SMTP.
type SMTPStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               SMTPObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SMTP is the Schema for the SMTPs API. SMTP configuration for a realm (a singleton; create == update upsert).
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,skycloak}
type SMTP struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.authType) || (has(self.initProvider) && has(self.initProvider.authType))",message="spec.forProvider.authType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.fromEmail) || (has(self.initProvider) && has(self.initProvider.fromEmail))",message="spec.forProvider.fromEmail is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.host) || (has(self.initProvider) && has(self.initProvider.host))",message="spec.forProvider.host is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.port) || (has(self.initProvider) && has(self.initProvider.port))",message="spec.forProvider.port is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.realmName) || (has(self.initProvider) && has(self.initProvider.realmName))",message="spec.forProvider.realmName is a required parameter"
	Spec   SMTPSpec   `json:"spec"`
	Status SMTPStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SMTPList contains a list of SMTPs
type SMTPList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SMTP `json:"items"`
}

// Repository type metadata.
var (
	SMTP_Kind             = "SMTP"
	SMTP_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SMTP_Kind}.String()
	SMTP_KindAPIVersion   = SMTP_Kind + "." + CRDGroupVersion.String()
	SMTP_GroupVersionKind = CRDGroupVersion.WithKind(SMTP_Kind)
)

func init() {
	SchemeBuilder.Register(&SMTP{}, &SMTPList{})
}
