/*
Copyright 2026 Decade Engineering
*/

// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ApplicationInitParameters struct {

	// (String) OAuth client ID (unique within the realm). Immutable.
	// OAuth client ID (unique within the realm). Immutable.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/namespaced/skycloak/v1alpha1.Cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (Boolean) Require user consent. Defaults to false.
	// Require user consent. Defaults to `false`.
	ConsentRequired *bool `json:"consentRequired,omitempty" tf:"consent_required,omitempty"`

	// (String) Description.
	// Description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (List of String) OAuth grant types enabled for the client.
	// OAuth grant types enabled for the client.
	GrantTypes []*string `json:"grantTypes,omitempty" tf:"grant_types,omitempty"`

	// (String) Display name.
	// Display name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Require PKCE. Defaults to false.
	// Require PKCE. Defaults to `false`.
	PkceRequired *bool `json:"pkceRequired,omitempty" tf:"pkce_required,omitempty"`

	// connect or saml. Immutable.
	// Protocol: `openid-connect` or `saml`. Immutable.
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`

	// (List of String) Allowed redirect URIs.
	// Allowed redirect URIs.
	RedirectUris []*string `json:"redirectUris,omitempty" tf:"redirect_uris,omitempty"`

	// (String) Client type: confidential or public. Immutable.
	// Client type: `confidential` or `public`. Immutable.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ApplicationObservation struct {

	// (String) OAuth client ID (unique within the realm). Immutable.
	// OAuth client ID (unique within the realm). Immutable.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (Boolean) Require user consent. Defaults to false.
	// Require user consent. Defaults to `false`.
	ConsentRequired *bool `json:"consentRequired,omitempty" tf:"consent_required,omitempty"`

	// (String) Creation timestamp.
	// Creation timestamp.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) Description.
	// Description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (List of String) OAuth grant types enabled for the client.
	// OAuth grant types enabled for the client.
	GrantTypes []*string `json:"grantTypes,omitempty" tf:"grant_types,omitempty"`

	// (String) Composite ID cluster_id/realm_name/client_id.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Display name.
	// Display name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Require PKCE. Defaults to false.
	// Require PKCE. Defaults to `false`.
	PkceRequired *bool `json:"pkceRequired,omitempty" tf:"pkce_required,omitempty"`

	// connect or saml. Immutable.
	// Protocol: `openid-connect` or `saml`. Immutable.
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`

	// (List of String) Allowed redirect URIs.
	// Allowed redirect URIs.
	RedirectUris []*string `json:"redirectUris,omitempty" tf:"redirect_uris,omitempty"`

	// only.
	// Whether a service account (client credentials) is enabled. Read-only.
	ServiceAccountEnabled *bool `json:"serviceAccountEnabled,omitempty" tf:"service_account_enabled,omitempty"`

	// (String) Status (active/inactive).
	// Status (`active`/`inactive`).
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (String) Client type: confidential or public. Immutable.
	// Client type: `confidential` or `public`. Immutable.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) Last update timestamp.
	// Last update timestamp.
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type ApplicationParameters struct {

	// (String) OAuth client ID (unique within the realm). Immutable.
	// OAuth client ID (unique within the realm). Immutable.
	// +kubebuilder:validation:Optional
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/namespaced/skycloak/v1alpha1.Cluster
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (Boolean) Require user consent. Defaults to false.
	// Require user consent. Defaults to `false`.
	// +kubebuilder:validation:Optional
	ConsentRequired *bool `json:"consentRequired,omitempty" tf:"consent_required,omitempty"`

	// (String) Description.
	// Description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (List of String) OAuth grant types enabled for the client.
	// OAuth grant types enabled for the client.
	// +kubebuilder:validation:Optional
	GrantTypes []*string `json:"grantTypes,omitempty" tf:"grant_types,omitempty"`

	// (String) Display name.
	// Display name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Require PKCE. Defaults to false.
	// Require PKCE. Defaults to `false`.
	// +kubebuilder:validation:Optional
	PkceRequired *bool `json:"pkceRequired,omitempty" tf:"pkce_required,omitempty"`

	// connect or saml. Immutable.
	// Protocol: `openid-connect` or `saml`. Immutable.
	// +kubebuilder:validation:Optional
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	// +kubebuilder:validation:Optional
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`

	// (List of String) Allowed redirect URIs.
	// Allowed redirect URIs.
	// +kubebuilder:validation:Optional
	RedirectUris []*string `json:"redirectUris,omitempty" tf:"redirect_uris,omitempty"`

	// (String) Client type: confidential or public. Immutable.
	// Client type: `confidential` or `public`. Immutable.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// ApplicationSpec defines the desired state of Application
type ApplicationSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ApplicationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ApplicationInitParameters `json:"initProvider,omitempty"`
}

// ApplicationStatus defines the observed state of Application.
type ApplicationStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ApplicationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Application is the Schema for the Applications API. An OIDC/SAML client (application) in a Skycloak realm.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,skycloak}
type Application struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.clientId) || (has(self.initProvider) && has(self.initProvider.clientId))",message="spec.forProvider.clientId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.realmName) || (has(self.initProvider) && has(self.initProvider.realmName))",message="spec.forProvider.realmName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   ApplicationSpec   `json:"spec"`
	Status ApplicationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ApplicationList contains a list of Applications
type ApplicationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Application `json:"items"`
}

// Repository type metadata.
var (
	Application_Kind             = "Application"
	Application_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Application_Kind}.String()
	Application_KindAPIVersion   = Application_Kind + "." + CRDGroupVersion.String()
	Application_GroupVersionKind = CRDGroupVersion.WithKind(Application_Kind)
)

func init() {
	SchemeBuilder.Register(&Application{}, &ApplicationList{})
}
