/*
Copyright 2026 Decade Engineering
*/

// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ApplicationSecretInitParameters struct {

	// (String) Application client ID. Immutable.
	// Application client ID. Immutable.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/namespaced/skycloak/v1alpha1.Cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`

	// (Map of String) Arbitrary key/value map; changing any value forces a new secret to be generated.
	// Arbitrary key/value map; changing any value forces a new secret to be generated.
	// +mapType=granular
	RotateWhen map[string]*string `json:"rotateWhen,omitempty" tf:"rotate_when,omitempty"`
}

type ApplicationSecretObservation struct {

	// (String) Application client ID. Immutable.
	// Application client ID. Immutable.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (String) Composite ID cluster_id/realm_name/client_id.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`

	// (Map of String) Arbitrary key/value map; changing any value forces a new secret to be generated.
	// Arbitrary key/value map; changing any value forces a new secret to be generated.
	// +mapType=granular
	RotateWhen map[string]*string `json:"rotateWhen,omitempty" tf:"rotate_when,omitempty"`
}

type ApplicationSecretParameters struct {

	// (String) Application client ID. Immutable.
	// Application client ID. Immutable.
	// +kubebuilder:validation:Optional
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/namespaced/skycloak/v1alpha1.Cluster
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	// +kubebuilder:validation:Optional
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`

	// (Map of String) Arbitrary key/value map; changing any value forces a new secret to be generated.
	// Arbitrary key/value map; changing any value forces a new secret to be generated.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	RotateWhen map[string]*string `json:"rotateWhen,omitempty" tf:"rotate_when,omitempty"`
}

// ApplicationSecretSpec defines the desired state of ApplicationSecret
type ApplicationSecretSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ApplicationSecretParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ApplicationSecretInitParameters `json:"initProvider,omitempty"`
}

// ApplicationSecretStatus defines the observed state of ApplicationSecret.
type ApplicationSecretStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ApplicationSecretObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ApplicationSecret is the Schema for the ApplicationSecrets API. Rotates an application's client secret. The secret is regenerated whenever this resource is created or rotate_when changes.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,skycloak}
type ApplicationSecret struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.clientId) || (has(self.initProvider) && has(self.initProvider.clientId))",message="spec.forProvider.clientId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.realmName) || (has(self.initProvider) && has(self.initProvider.realmName))",message="spec.forProvider.realmName is a required parameter"
	Spec   ApplicationSecretSpec   `json:"spec"`
	Status ApplicationSecretStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ApplicationSecretList contains a list of ApplicationSecrets
type ApplicationSecretList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ApplicationSecret `json:"items"`
}

// Repository type metadata.
var (
	ApplicationSecret_Kind             = "ApplicationSecret"
	ApplicationSecret_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ApplicationSecret_Kind}.String()
	ApplicationSecret_KindAPIVersion   = ApplicationSecret_Kind + "." + CRDGroupVersion.String()
	ApplicationSecret_GroupVersionKind = CRDGroupVersion.WithKind(ApplicationSecret_Kind)
)

func init() {
	SchemeBuilder.Register(&ApplicationSecret{}, &ApplicationSecretList{})
}
