/*
Copyright 2026 Decade Engineering
*/

// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ClusterExtensionInitParameters struct {

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/namespaced/skycloak/v1alpha1.Cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (String) Catalog extension ID (see the skycloak_extensions data source). Immutable.
	// Catalog extension ID (see the `skycloak_extensions` data source). Immutable.
	ExtensionID *string `json:"extensionId,omitempty" tf:"extension_id,omitempty"`

	Parameters map[string]*string `json:"parametersSecretRef,omitempty" tf:"-"`
}

type ClusterExtensionObservation struct {

	// (String) Latest available version.
	// Latest available version.
	AvailableVersion *string `json:"availableVersion,omitempty" tf:"available_version,omitempty"`

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (String) Catalog extension ID (see the skycloak_extensions data source). Immutable.
	// Catalog extension ID (see the `skycloak_extensions` data source). Immutable.
	ExtensionID *string `json:"extensionId,omitempty" tf:"extension_id,omitempty"`

	// (String) Extension display name.
	// Extension display name.
	ExtensionName *string `json:"extensionName,omitempty" tf:"extension_name,omitempty"`

	// (String) Composite ID cluster_id/extension_id.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Install timestamp (RFC 3339).
	// Install timestamp (RFC 3339).
	InstalledAt *string `json:"installedAt,omitempty" tf:"installed_at,omitempty"`

	// (String) Version currently running on the cluster.
	// Version currently running on the cluster.
	InstalledVersion *string `json:"installedVersion,omitempty" tf:"installed_version,omitempty"`

	// (String) Extension source (marketplace, custom).
	// Extension source (`marketplace`, `custom`).
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// (String) Installation status.
	// Installation status.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (Boolean) Whether a newer version is available.
	// Whether a newer version is available.
	UpgradeAvailable *bool `json:"upgradeAvailable,omitempty" tf:"upgrade_available,omitempty"`
}

type ClusterExtensionParameters struct {

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/namespaced/skycloak/v1alpha1.Cluster
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (String) Catalog extension ID (see the skycloak_extensions data source). Immutable.
	// Catalog extension ID (see the `skycloak_extensions` data source). Immutable.
	// +kubebuilder:validation:Optional
	ExtensionID *string `json:"extensionId,omitempty" tf:"extension_id,omitempty"`

	// only (sensitive values are never read back). Changing this reinstalls the extension.
	// Parameter values keyed by parameter `key`. Write-only (sensitive values are never read back). Changing this reinstalls the extension.
	// +kubebuilder:validation:Optional
	ParametersSecretRef *v2.LocalSecretReference `json:"parametersSecretRef,omitempty" tf:"-"`
}

// ClusterExtensionSpec defines the desired state of ClusterExtension
type ClusterExtensionSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ClusterExtensionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ClusterExtensionInitParameters `json:"initProvider,omitempty"`
}

// ClusterExtensionStatus defines the observed state of ClusterExtension.
type ClusterExtensionStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ClusterExtensionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ClusterExtension is the Schema for the ClusterExtensions API. Installs a marketplace extension on a cluster. Installation is asynchronous; the status reflects provisioning progress. Changing extension_id or parameters reinstalls the extension.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,skycloak}
type ClusterExtension struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.extensionId) || (has(self.initProvider) && has(self.initProvider.extensionId))",message="spec.forProvider.extensionId is a required parameter"
	Spec   ClusterExtensionSpec   `json:"spec"`
	Status ClusterExtensionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ClusterExtensionList contains a list of ClusterExtensions
type ClusterExtensionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ClusterExtension `json:"items"`
}

// Repository type metadata.
var (
	ClusterExtension_Kind             = "ClusterExtension"
	ClusterExtension_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ClusterExtension_Kind}.String()
	ClusterExtension_KindAPIVersion   = ClusterExtension_Kind + "." + CRDGroupVersion.String()
	ClusterExtension_GroupVersionKind = CRDGroupVersion.WithKind(ClusterExtension_Kind)
)

func init() {
	SchemeBuilder.Register(&ClusterExtension{}, &ClusterExtensionList{})
}
