/*
Copyright 2026 Decade Engineering
*/

// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ClusterInitParameters struct {

	// (Boolean) Enable automatic patch upgrades, applied inside the cluster's maintenance window. Defaults to false.
	// Enable automatic patch upgrades, applied inside the cluster's maintenance window. Defaults to `false`.
	AutoUpgradeEnabled *bool `json:"autoUpgradeEnabled,omitempty" tf:"auto_upgrade_enabled,omitempty"`

	// (String) Region (us, ca, eu, au). Immutable — changing it replaces the cluster.
	// Region (`us`, `ca`, `eu`, `au`). Immutable — changing it replaces the cluster.
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// readable cluster name.
	// Human-readable cluster name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Instance size (small, medium, large).
	// Instance size (`small`, `medium`, `large`).
	Size *string `json:"size,omitempty" tf:"size,omitempty"`

	// (String) Cluster type (keycloak or tidecloak). Immutable — changing it replaces the cluster.
	// Cluster type (`keycloak` or `tidecloak`). Immutable — changing it replaces the cluster.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) Keycloak version, e.g. 26.1.
	// Keycloak version, e.g. `26.1`.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type ClusterObservation struct {

	// (Boolean) Enable automatic patch upgrades, applied inside the cluster's maintenance window. Defaults to false.
	// Enable automatic patch upgrades, applied inside the cluster's maintenance window. Defaults to `false`.
	AutoUpgradeEnabled *bool `json:"autoUpgradeEnabled,omitempty" tf:"auto_upgrade_enabled,omitempty"`

	// (String) Cluster ID (UUID).
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Region (us, ca, eu, au). Immutable — changing it replaces the cluster.
	// Region (`us`, `ca`, `eu`, `au`). Immutable — changing it replaces the cluster.
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// readable cluster name.
	// Human-readable cluster name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Instance size (small, medium, large).
	// Instance size (`small`, `medium`, `large`).
	Size *string `json:"size,omitempty" tf:"size,omitempty"`

	// (String) Lifecycle status (provisioning, available, ...).
	// Lifecycle status (`provisioning`, `available`, ...).
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (String) Cluster type (keycloak or tidecloak). Immutable — changing it replaces the cluster.
	// Cluster type (`keycloak` or `tidecloak`). Immutable — changing it replaces the cluster.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) Cluster base URL once available.
	// Cluster base URL once available.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// (String) Keycloak version, e.g. 26.1.
	// Keycloak version, e.g. `26.1`.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type ClusterParameters struct {

	// (Boolean) Enable automatic patch upgrades, applied inside the cluster's maintenance window. Defaults to false.
	// Enable automatic patch upgrades, applied inside the cluster's maintenance window. Defaults to `false`.
	// +kubebuilder:validation:Optional
	AutoUpgradeEnabled *bool `json:"autoUpgradeEnabled,omitempty" tf:"auto_upgrade_enabled,omitempty"`

	// (String) Region (us, ca, eu, au). Immutable — changing it replaces the cluster.
	// Region (`us`, `ca`, `eu`, `au`). Immutable — changing it replaces the cluster.
	// +kubebuilder:validation:Optional
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// readable cluster name.
	// Human-readable cluster name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Instance size (small, medium, large).
	// Instance size (`small`, `medium`, `large`).
	// +kubebuilder:validation:Optional
	Size *string `json:"size,omitempty" tf:"size,omitempty"`

	// (String) Cluster type (keycloak or tidecloak). Immutable — changing it replaces the cluster.
	// Cluster type (`keycloak` or `tidecloak`). Immutable — changing it replaces the cluster.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) Keycloak version, e.g. 26.1.
	// Keycloak version, e.g. `26.1`.
	// +kubebuilder:validation:Optional
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

// ClusterSpec defines the desired state of Cluster
type ClusterSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ClusterParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ClusterInitParameters `json:"initProvider,omitempty"`
}

// ClusterStatus defines the observed state of Cluster.
type ClusterStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ClusterObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Cluster is the Schema for the Clusters API. A Skycloak managed Keycloak cluster.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,skycloak}
type Cluster struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.location) || (has(self.initProvider) && has(self.initProvider.location))",message="spec.forProvider.location is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.size) || (has(self.initProvider) && has(self.initProvider.size))",message="spec.forProvider.size is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.version) || (has(self.initProvider) && has(self.initProvider.version))",message="spec.forProvider.version is a required parameter"
	Spec   ClusterSpec   `json:"spec"`
	Status ClusterStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ClusterList contains a list of Clusters
type ClusterList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Cluster `json:"items"`
}

// Repository type metadata.
var (
	Cluster_Kind             = "Cluster"
	Cluster_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Cluster_Kind}.String()
	Cluster_KindAPIVersion   = Cluster_Kind + "." + CRDGroupVersion.String()
	Cluster_GroupVersionKind = CRDGroupVersion.WithKind(Cluster_Kind)
)

func init() {
	SchemeBuilder.Register(&Cluster{}, &ClusterList{})
}
