/*
Copyright 2026 Decade Engineering
*/

// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type EmailBrandingInitParameters struct {

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/namespaced/skycloak/v1alpha1.Cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (String) URL linked from the email footer.
	// URL linked from the email footer.
	CompanyURL *string `json:"companyUrl,omitempty" tf:"company_url,omitempty"`

	// (String) Company name shown in the email footer.
	// Company name shown in the email footer.
	FooterCompanyName *string `json:"footerCompanyName,omitempty" tf:"footer_company_name,omitempty"`

	// text shown in the email footer.
	// Free-text shown in the email footer.
	FooterText *string `json:"footerText,omitempty" tf:"footer_text,omitempty"`

	// background email clients.
	// Logo URL for dark-background email clients.
	HeaderLogoDarkURL *string `json:"headerLogoDarkUrl,omitempty" tf:"header_logo_dark_url,omitempty"`

	// background email clients.
	// Logo URL for light-background email clients.
	HeaderLogoLightURL *string `json:"headerLogoLightUrl,omitempty" tf:"header_logo_light_url,omitempty"`

	// (Attributes) Email internationalization settings. (see below for nested schema)
	Internationalization *InternationalizationInitParameters `json:"internationalization,omitempty" tf:"internationalization,omitempty"`

	// (String) Primary accent color (hex, e.g. #0ea5e9).
	// Primary accent color (hex, e.g. `#0ea5e9`).
	PrimaryColor *string `json:"primaryColor,omitempty" tf:"primary_color,omitempty"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`
}

type EmailBrandingObservation struct {

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (String) URL linked from the email footer.
	// URL linked from the email footer.
	CompanyURL *string `json:"companyUrl,omitempty" tf:"company_url,omitempty"`

	// (String) Company name shown in the email footer.
	// Company name shown in the email footer.
	FooterCompanyName *string `json:"footerCompanyName,omitempty" tf:"footer_company_name,omitempty"`

	// text shown in the email footer.
	// Free-text shown in the email footer.
	FooterText *string `json:"footerText,omitempty" tf:"footer_text,omitempty"`

	// background email clients.
	// Logo URL for dark-background email clients.
	HeaderLogoDarkURL *string `json:"headerLogoDarkUrl,omitempty" tf:"header_logo_dark_url,omitempty"`

	// background email clients.
	// Logo URL for light-background email clients.
	HeaderLogoLightURL *string `json:"headerLogoLightUrl,omitempty" tf:"header_logo_light_url,omitempty"`

	// (String) Composite ID cluster_id/realm_name/email_branding.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Attributes) Email internationalization settings. (see below for nested schema)
	Internationalization *InternationalizationObservation `json:"internationalization,omitempty" tf:"internationalization,omitempty"`

	// (String) Primary accent color (hex, e.g. #0ea5e9).
	// Primary accent color (hex, e.g. `#0ea5e9`).
	PrimaryColor *string `json:"primaryColor,omitempty" tf:"primary_color,omitempty"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`

	// (String) Deployment status (applied, applying, failed).
	// Deployment status (`applied`, `applying`, `failed`).
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type EmailBrandingParameters struct {

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/namespaced/skycloak/v1alpha1.Cluster
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (String) URL linked from the email footer.
	// URL linked from the email footer.
	// +kubebuilder:validation:Optional
	CompanyURL *string `json:"companyUrl,omitempty" tf:"company_url,omitempty"`

	// (String) Company name shown in the email footer.
	// Company name shown in the email footer.
	// +kubebuilder:validation:Optional
	FooterCompanyName *string `json:"footerCompanyName,omitempty" tf:"footer_company_name,omitempty"`

	// text shown in the email footer.
	// Free-text shown in the email footer.
	// +kubebuilder:validation:Optional
	FooterText *string `json:"footerText,omitempty" tf:"footer_text,omitempty"`

	// background email clients.
	// Logo URL for dark-background email clients.
	// +kubebuilder:validation:Optional
	HeaderLogoDarkURL *string `json:"headerLogoDarkUrl,omitempty" tf:"header_logo_dark_url,omitempty"`

	// background email clients.
	// Logo URL for light-background email clients.
	// +kubebuilder:validation:Optional
	HeaderLogoLightURL *string `json:"headerLogoLightUrl,omitempty" tf:"header_logo_light_url,omitempty"`

	// (Attributes) Email internationalization settings. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Internationalization *InternationalizationParameters `json:"internationalization,omitempty" tf:"internationalization,omitempty"`

	// (String) Primary accent color (hex, e.g. #0ea5e9).
	// Primary accent color (hex, e.g. `#0ea5e9`).
	// +kubebuilder:validation:Optional
	PrimaryColor *string `json:"primaryColor,omitempty" tf:"primary_color,omitempty"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	// +kubebuilder:validation:Optional
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`
}

type InternationalizationInitParameters struct {

	// (String) Default locale (BCP 47 tag, e.g. en).
	// Default locale (BCP 47 tag, e.g. `en`).
	DefaultLocale *string `json:"defaultLocale,omitempty" tf:"default_locale,omitempty"`

	// (Boolean) Whether internationalization is enabled.
	// Whether internationalization is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (List of String) Locales available to users. Must include default_locale.
	// Locales available to users. Must include `default_locale`.
	SupportedLocales []*string `json:"supportedLocales,omitempty" tf:"supported_locales,omitempty"`
}

type InternationalizationObservation struct {

	// (String) Default locale (BCP 47 tag, e.g. en).
	// Default locale (BCP 47 tag, e.g. `en`).
	DefaultLocale *string `json:"defaultLocale,omitempty" tf:"default_locale,omitempty"`

	// (Boolean) Whether internationalization is enabled.
	// Whether internationalization is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (List of String) Locales available to users. Must include default_locale.
	// Locales available to users. Must include `default_locale`.
	SupportedLocales []*string `json:"supportedLocales,omitempty" tf:"supported_locales,omitempty"`
}

type InternationalizationParameters struct {

	// (String) Default locale (BCP 47 tag, e.g. en).
	// Default locale (BCP 47 tag, e.g. `en`).
	// +kubebuilder:validation:Optional
	DefaultLocale *string `json:"defaultLocale" tf:"default_locale,omitempty"`

	// (Boolean) Whether internationalization is enabled.
	// Whether internationalization is enabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled" tf:"enabled,omitempty"`

	// (List of String) Locales available to users. Must include default_locale.
	// Locales available to users. Must include `default_locale`.
	// +kubebuilder:validation:Optional
	SupportedLocales []*string `json:"supportedLocales" tf:"supported_locales,omitempty"`
}

// EmailBrandingSpec defines the desired state of EmailBranding
type EmailBrandingSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            EmailBrandingParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider EmailBrandingInitParameters `json:"initProvider,omitempty"`
}

// EmailBrandingStatus defines the observed state of EmailBranding.
type EmailBrandingStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               EmailBrandingObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// EmailBranding is the Schema for the EmailBrandings API. Email-template branding for a realm (a singleton; create == update upsert).
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,skycloak}
type EmailBranding struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.realmName) || (has(self.initProvider) && has(self.initProvider.realmName))",message="spec.forProvider.realmName is a required parameter"
	Spec   EmailBrandingSpec   `json:"spec"`
	Status EmailBrandingStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// EmailBrandingList contains a list of EmailBrandings
type EmailBrandingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []EmailBranding `json:"items"`
}

// Repository type metadata.
var (
	EmailBranding_Kind             = "EmailBranding"
	EmailBranding_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: EmailBranding_Kind}.String()
	EmailBranding_KindAPIVersion   = EmailBranding_Kind + "." + CRDGroupVersion.String()
	EmailBranding_GroupVersionKind = CRDGroupVersion.WithKind(EmailBranding_Kind)
)

func init() {
	SchemeBuilder.Register(&EmailBranding{}, &EmailBrandingList{})
}
