/*
Copyright 2026 Decade Engineering
*/

// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ConfigInitParameters struct {

	// (Map of String) Keycloak attribute → IdP claim mappings.
	// Keycloak attribute → IdP claim mappings.
	// +mapType=granular
	AttributeMappings map[string]*string `json:"attributeMappings,omitempty" tf:"attribute_mappings,omitempty"`

	// (String) Login button label.
	// Login button label.
	ButtonText *string `json:"buttonText,omitempty" tf:"button_text,omitempty"`

	// (String) Login button icon URL.
	// Login button icon URL.
	IconURL *string `json:"iconUrl,omitempty" tf:"icon_url,omitempty"`

	// (Attributes) LDAP settings (when type is ldap). (see below for nested schema)
	Ldap *LdapInitParameters `json:"ldap,omitempty" tf:"ldap,omitempty"`

	// (Attributes) OIDC endpoints (when type is oidc). (see below for nested schema)
	Oidc *OidcInitParameters `json:"oidc,omitempty" tf:"oidc,omitempty"`

	// (Attributes) SAML settings (when type is saml). (see below for nested schema)
	SAML *SAMLInitParameters `json:"saml,omitempty" tf:"saml,omitempty"`

	// (String) User profile sync mode (IMPORT, LEGACY, FORCE).
	// User profile sync mode (`IMPORT`, `LEGACY`, `FORCE`).
	SyncMode *string `json:"syncMode,omitempty" tf:"sync_mode,omitempty"`

	// (Boolean) Trust email addresses from this provider.
	// Trust email addresses from this provider.
	TrustEmail *bool `json:"trustEmail,omitempty" tf:"trust_email,omitempty"`
}

type ConfigObservation struct {

	// (Map of String) Keycloak attribute → IdP claim mappings.
	// Keycloak attribute → IdP claim mappings.
	// +mapType=granular
	AttributeMappings map[string]*string `json:"attributeMappings,omitempty" tf:"attribute_mappings,omitempty"`

	// (String) Login button label.
	// Login button label.
	ButtonText *string `json:"buttonText,omitempty" tf:"button_text,omitempty"`

	// (String) Login button icon URL.
	// Login button icon URL.
	IconURL *string `json:"iconUrl,omitempty" tf:"icon_url,omitempty"`

	// (Attributes) LDAP settings (when type is ldap). (see below for nested schema)
	Ldap *LdapObservation `json:"ldap,omitempty" tf:"ldap,omitempty"`

	// (Attributes) OIDC endpoints (when type is oidc). (see below for nested schema)
	Oidc *OidcObservation `json:"oidc,omitempty" tf:"oidc,omitempty"`

	// (Attributes) SAML settings (when type is saml). (see below for nested schema)
	SAML *SAMLObservation `json:"saml,omitempty" tf:"saml,omitempty"`

	// (String) User profile sync mode (IMPORT, LEGACY, FORCE).
	// User profile sync mode (`IMPORT`, `LEGACY`, `FORCE`).
	SyncMode *string `json:"syncMode,omitempty" tf:"sync_mode,omitempty"`

	// (Boolean) Trust email addresses from this provider.
	// Trust email addresses from this provider.
	TrustEmail *bool `json:"trustEmail,omitempty" tf:"trust_email,omitempty"`
}

type ConfigParameters struct {

	// (Map of String) Keycloak attribute → IdP claim mappings.
	// Keycloak attribute → IdP claim mappings.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	AttributeMappings map[string]*string `json:"attributeMappings,omitempty" tf:"attribute_mappings,omitempty"`

	// (String) Login button label.
	// Login button label.
	// +kubebuilder:validation:Optional
	ButtonText *string `json:"buttonText,omitempty" tf:"button_text,omitempty"`

	// (String) Login button icon URL.
	// Login button icon URL.
	// +kubebuilder:validation:Optional
	IconURL *string `json:"iconUrl,omitempty" tf:"icon_url,omitempty"`

	// (Attributes) LDAP settings (when type is ldap). (see below for nested schema)
	// +kubebuilder:validation:Optional
	Ldap *LdapParameters `json:"ldap,omitempty" tf:"ldap,omitempty"`

	// (Attributes) OIDC endpoints (when type is oidc). (see below for nested schema)
	// +kubebuilder:validation:Optional
	Oidc *OidcParameters `json:"oidc,omitempty" tf:"oidc,omitempty"`

	// (Attributes) SAML settings (when type is saml). (see below for nested schema)
	// +kubebuilder:validation:Optional
	SAML *SAMLParameters `json:"saml,omitempty" tf:"saml,omitempty"`

	// (String) User profile sync mode (IMPORT, LEGACY, FORCE).
	// User profile sync mode (`IMPORT`, `LEGACY`, `FORCE`).
	// +kubebuilder:validation:Optional
	SyncMode *string `json:"syncMode,omitempty" tf:"sync_mode,omitempty"`

	// (Boolean) Trust email addresses from this provider.
	// Trust email addresses from this provider.
	// +kubebuilder:validation:Optional
	TrustEmail *bool `json:"trustEmail,omitempty" tf:"trust_email,omitempty"`
}

type IdentityProviderInitParameters struct {

	// (String) Upstream client/application ID.
	// Upstream client/application ID.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// only; never read back.
	// Upstream client secret. Write-only; never read back.
	ClientSecretSecretRef *v2.LocalSecretKeySelector `json:"clientSecretSecretRef,omitempty" tf:"-"`

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/namespaced/skycloak/v1alpha1.Cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (Attributes) Provider configuration. (see below for nested schema)
	Config *ConfigInitParameters `json:"config,omitempty" tf:"config,omitempty"`

	// (String) Display name shown on the login page.
	// Display name shown on the login page.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Boolean) Whether the provider is enabled. Defaults to true.
	// Whether the provider is enabled. Defaults to `true`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Unique provider alias within the realm. Immutable.
	// Unique provider alias within the realm. Immutable.
	ProviderID *string `json:"providerId,omitempty" tf:"provider_id,omitempty"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`

	// (String) Provider kind: oidc, saml, or ldap. Immutable.
	// Provider kind: `oidc`, `saml`, or `ldap`. Immutable.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type IdentityProviderObservation struct {

	// (String) Upstream client/application ID.
	// Upstream client/application ID.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (Attributes) Provider configuration. (see below for nested schema)
	Config *ConfigObservation `json:"config,omitempty" tf:"config,omitempty"`

	// (String) Creation timestamp.
	// Creation timestamp.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) Display name shown on the login page.
	// Display name shown on the login page.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Boolean) Whether the provider is enabled. Defaults to true.
	// Whether the provider is enabled. Defaults to `true`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Boolean) True if the provider is managed outside Skycloak; such providers reject updates and deletes.
	// True if the provider is managed outside Skycloak; such providers reject updates and deletes.
	ExternallyManaged *bool `json:"externallyManaged,omitempty" tf:"externally_managed,omitempty"`

	// (String) Composite ID cluster_id/realm_name/provider_id.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Unique provider alias within the realm. Immutable.
	// Unique provider alias within the realm. Immutable.
	ProviderID *string `json:"providerId,omitempty" tf:"provider_id,omitempty"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`

	// (String) Provider kind: oidc, saml, or ldap. Immutable.
	// Provider kind: `oidc`, `saml`, or `ldap`. Immutable.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) Last update timestamp.
	// Last update timestamp.
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type IdentityProviderParameters struct {

	// (String) Upstream client/application ID.
	// Upstream client/application ID.
	// +kubebuilder:validation:Optional
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// only; never read back.
	// Upstream client secret. Write-only; never read back.
	// +kubebuilder:validation:Optional
	ClientSecretSecretRef *v2.LocalSecretKeySelector `json:"clientSecretSecretRef,omitempty" tf:"-"`

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/namespaced/skycloak/v1alpha1.Cluster
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (Attributes) Provider configuration. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Config *ConfigParameters `json:"config,omitempty" tf:"config,omitempty"`

	// (String) Display name shown on the login page.
	// Display name shown on the login page.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Boolean) Whether the provider is enabled. Defaults to true.
	// Whether the provider is enabled. Defaults to `true`.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Unique provider alias within the realm. Immutable.
	// Unique provider alias within the realm. Immutable.
	// +kubebuilder:validation:Optional
	ProviderID *string `json:"providerId,omitempty" tf:"provider_id,omitempty"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	// +kubebuilder:validation:Optional
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`

	// (String) Provider kind: oidc, saml, or ldap. Immutable.
	// Provider kind: `oidc`, `saml`, or `ldap`. Immutable.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type LdapInitParameters struct {

	// (String) Base DN.
	// Base DN.
	BaseDn *string `json:"baseDn,omitempty" tf:"base_dn,omitempty"`

	// (String) Bind DN.
	// Bind DN.
	BindDn *string `json:"bindDn,omitempty" tf:"bind_dn,omitempty"`

	// (String) LDAP server URL.
	// LDAP server URL.
	ServerURL *string `json:"serverUrl,omitempty" tf:"server_url,omitempty"`
}

type LdapObservation struct {

	// (String) Base DN.
	// Base DN.
	BaseDn *string `json:"baseDn,omitempty" tf:"base_dn,omitempty"`

	// (String) Bind DN.
	// Bind DN.
	BindDn *string `json:"bindDn,omitempty" tf:"bind_dn,omitempty"`

	// (String) LDAP server URL.
	// LDAP server URL.
	ServerURL *string `json:"serverUrl,omitempty" tf:"server_url,omitempty"`
}

type LdapParameters struct {

	// (String) Base DN.
	// Base DN.
	// +kubebuilder:validation:Optional
	BaseDn *string `json:"baseDn,omitempty" tf:"base_dn,omitempty"`

	// (String) Bind DN.
	// Bind DN.
	// +kubebuilder:validation:Optional
	BindDn *string `json:"bindDn,omitempty" tf:"bind_dn,omitempty"`

	// (String) LDAP server URL.
	// LDAP server URL.
	// +kubebuilder:validation:Optional
	ServerURL *string `json:"serverUrl,omitempty" tf:"server_url,omitempty"`
}

type OidcInitParameters struct {

	// (String) Authorization endpoint URL.
	// Authorization endpoint URL.
	AuthorizationURL *string `json:"authorizationUrl,omitempty" tf:"authorization_url,omitempty"`

	// (String) Issuer URL.
	// Issuer URL.
	Issuer *string `json:"issuer,omitempty" tf:"issuer,omitempty"`

	// (String) Logout endpoint URL.
	// Logout endpoint URL.
	LogoutURL *string `json:"logoutUrl,omitempty" tf:"logout_url,omitempty"`

	// (String) Token endpoint URL.
	// Token endpoint URL.
	TokenURL *string `json:"tokenUrl,omitempty" tf:"token_url,omitempty"`

	// (String) Userinfo endpoint URL.
	// Userinfo endpoint URL.
	UserinfoURL *string `json:"userinfoUrl,omitempty" tf:"userinfo_url,omitempty"`
}

type OidcObservation struct {

	// (String) Authorization endpoint URL.
	// Authorization endpoint URL.
	AuthorizationURL *string `json:"authorizationUrl,omitempty" tf:"authorization_url,omitempty"`

	// (String) Issuer URL.
	// Issuer URL.
	Issuer *string `json:"issuer,omitempty" tf:"issuer,omitempty"`

	// (String) Logout endpoint URL.
	// Logout endpoint URL.
	LogoutURL *string `json:"logoutUrl,omitempty" tf:"logout_url,omitempty"`

	// (String) Token endpoint URL.
	// Token endpoint URL.
	TokenURL *string `json:"tokenUrl,omitempty" tf:"token_url,omitempty"`

	// (String) Userinfo endpoint URL.
	// Userinfo endpoint URL.
	UserinfoURL *string `json:"userinfoUrl,omitempty" tf:"userinfo_url,omitempty"`
}

type OidcParameters struct {

	// (String) Authorization endpoint URL.
	// Authorization endpoint URL.
	// +kubebuilder:validation:Optional
	AuthorizationURL *string `json:"authorizationUrl,omitempty" tf:"authorization_url,omitempty"`

	// (String) Issuer URL.
	// Issuer URL.
	// +kubebuilder:validation:Optional
	Issuer *string `json:"issuer,omitempty" tf:"issuer,omitempty"`

	// (String) Logout endpoint URL.
	// Logout endpoint URL.
	// +kubebuilder:validation:Optional
	LogoutURL *string `json:"logoutUrl,omitempty" tf:"logout_url,omitempty"`

	// (String) Token endpoint URL.
	// Token endpoint URL.
	// +kubebuilder:validation:Optional
	TokenURL *string `json:"tokenUrl,omitempty" tf:"token_url,omitempty"`

	// (String) Userinfo endpoint URL.
	// Userinfo endpoint URL.
	// +kubebuilder:validation:Optional
	UserinfoURL *string `json:"userinfoUrl,omitempty" tf:"userinfo_url,omitempty"`
}

type SAMLInitParameters struct {

	// (String) IdP entity ID.
	// IdP entity ID.
	EntityID *string `json:"entityId,omitempty" tf:"entity_id,omitempty"`

	// (String) IdP metadata URL.
	// IdP metadata URL.
	MetadataURL *string `json:"metadataUrl,omitempty" tf:"metadata_url,omitempty"`

	// (String) IdP metadata XML.
	// IdP metadata XML.
	MetadataXML *string `json:"metadataXml,omitempty" tf:"metadata_xml,omitempty"`

	// on service URL.
	// Single sign-on service URL.
	SsoURL *string `json:"ssoUrl,omitempty" tf:"sso_url,omitempty"`
}

type SAMLObservation struct {

	// (String) IdP entity ID.
	// IdP entity ID.
	EntityID *string `json:"entityId,omitempty" tf:"entity_id,omitempty"`

	// (String) IdP metadata URL.
	// IdP metadata URL.
	MetadataURL *string `json:"metadataUrl,omitempty" tf:"metadata_url,omitempty"`

	// (String) IdP metadata XML.
	// IdP metadata XML.
	MetadataXML *string `json:"metadataXml,omitempty" tf:"metadata_xml,omitempty"`

	// on service URL.
	// Single sign-on service URL.
	SsoURL *string `json:"ssoUrl,omitempty" tf:"sso_url,omitempty"`
}

type SAMLParameters struct {

	// (String) IdP entity ID.
	// IdP entity ID.
	// +kubebuilder:validation:Optional
	EntityID *string `json:"entityId,omitempty" tf:"entity_id,omitempty"`

	// (String) IdP metadata URL.
	// IdP metadata URL.
	// +kubebuilder:validation:Optional
	MetadataURL *string `json:"metadataUrl,omitempty" tf:"metadata_url,omitempty"`

	// (String) IdP metadata XML.
	// IdP metadata XML.
	// +kubebuilder:validation:Optional
	MetadataXML *string `json:"metadataXml,omitempty" tf:"metadata_xml,omitempty"`

	// on service URL.
	// Single sign-on service URL.
	// +kubebuilder:validation:Optional
	SsoURL *string `json:"ssoUrl,omitempty" tf:"sso_url,omitempty"`
}

// IdentityProviderSpec defines the desired state of IdentityProvider
type IdentityProviderSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            IdentityProviderParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider IdentityProviderInitParameters `json:"initProvider,omitempty"`
}

// IdentityProviderStatus defines the observed state of IdentityProvider.
type IdentityProviderStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               IdentityProviderObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// IdentityProvider is the Schema for the IdentityProviders API. An identity provider (SSO connection) in a Skycloak realm.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,skycloak}
type IdentityProvider struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.config) || (has(self.initProvider) && has(self.initProvider.config))",message="spec.forProvider.config is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.providerId) || (has(self.initProvider) && has(self.initProvider.providerId))",message="spec.forProvider.providerId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.realmName) || (has(self.initProvider) && has(self.initProvider.realmName))",message="spec.forProvider.realmName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   IdentityProviderSpec   `json:"spec"`
	Status IdentityProviderStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// IdentityProviderList contains a list of IdentityProviders
type IdentityProviderList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []IdentityProvider `json:"items"`
}

// Repository type metadata.
var (
	IdentityProvider_Kind             = "IdentityProvider"
	IdentityProvider_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: IdentityProvider_Kind}.String()
	IdentityProvider_KindAPIVersion   = IdentityProvider_Kind + "." + CRDGroupVersion.String()
	IdentityProvider_GroupVersionKind = CRDGroupVersion.WithKind(IdentityProvider_Kind)
)

func init() {
	SchemeBuilder.Register(&IdentityProvider{}, &IdentityProviderList{})
}
