/*
Copyright 2026 Decade Engineering
*/

// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type RealmExportInitParameters struct {

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/namespaced/skycloak/v1alpha1.Cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`

	// 256-CBC, PBKDF2), 8-128 characters. Required: every realm export contains credentials. Write-only; never read back, so an imported resource plans a replacement until it is set. Immutable.
	// Password used to encrypt the archive (AES-256-CBC, PBKDF2), 8-128 characters. Required: every realm export contains credentials. Write-only; never read back, so an imported resource plans a replacement until it is set. Immutable.
	EncryptionPasswordSecretRef v2.LocalSecretKeySelector `json:"encryptionPasswordSecretRef" tf:"-"`

	// (String) Name of the realm to export. Immutable.
	// Name of the realm to export. Immutable.
	Realm *string `json:"realm,omitempty" tf:"realm,omitempty"`

	// (String) Export scope. Only full is currently supported. Immutable.
	// Export scope. Only `full` is currently supported. Immutable.
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

type RealmExportObservation struct {

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (String) Completion timestamp (RFC 3339).
	// Completion timestamp (RFC 3339).
	CompletedAt *string `json:"completedAt,omitempty" tf:"completed_at,omitempty"`

	// (String) Creation timestamp (RFC 3339).
	// Creation timestamp (RFC 3339).
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) When the archive is deleted from storage, 24h after completion (RFC 3339).
	// When the archive is deleted from storage, 24h after completion (RFC 3339).
	ExpiresAt *string `json:"expiresAt,omitempty" tf:"expires_at,omitempty"`

	// (String) Realm export job ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// 100).
	// Completion percentage (0-100).
	Progress *float64 `json:"progress,omitempty" tf:"progress,omitempty"`

	// (String) Name of the realm to export. Immutable.
	// Name of the realm to export. Immutable.
	Realm *string `json:"realm,omitempty" tf:"realm,omitempty"`

	// (String) Export scope. Only full is currently supported. Immutable.
	// Export scope. Only `full` is currently supported. Immutable.
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// 256 checksum of the encrypted archive (hex).
	// SHA-256 checksum of the encrypted archive (hex).
	Sha256Checksum *string `json:"sha256Checksum,omitempty" tf:"sha256_checksum,omitempty"`

	// (String) Keycloak version that produced the export. An import target must run this version or newer.
	// Keycloak version that produced the export. An import target must run this version or newer.
	SourceVersion *string `json:"sourceVersion,omitempty" tf:"source_version,omitempty"`

	// (String) Job status (pending, processing, completed, failed).
	// Job status (`pending`, `processing`, `completed`, `failed`).
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type RealmExportParameters struct {

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/namespaced/skycloak/v1alpha1.Cluster
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`

	// 256-CBC, PBKDF2), 8-128 characters. Required: every realm export contains credentials. Write-only; never read back, so an imported resource plans a replacement until it is set. Immutable.
	// Password used to encrypt the archive (AES-256-CBC, PBKDF2), 8-128 characters. Required: every realm export contains credentials. Write-only; never read back, so an imported resource plans a replacement until it is set. Immutable.
	// +kubebuilder:validation:Optional
	EncryptionPasswordSecretRef v2.LocalSecretKeySelector `json:"encryptionPasswordSecretRef" tf:"-"`

	// (String) Name of the realm to export. Immutable.
	// Name of the realm to export. Immutable.
	// +kubebuilder:validation:Optional
	Realm *string `json:"realm,omitempty" tf:"realm,omitempty"`

	// (String) Export scope. Only full is currently supported. Immutable.
	// Export scope. Only `full` is currently supported. Immutable.
	// +kubebuilder:validation:Optional
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

// RealmExportSpec defines the desired state of RealmExport
type RealmExportSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            RealmExportParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RealmExportInitParameters `json:"initProvider,omitempty"`
}

// RealmExportStatus defines the observed state of RealmExport.
type RealmExportStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               RealmExportObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RealmExport is the Schema for the RealmExports API. A one-shot export of a single realm (configuration, users, and credentials). Creating the resource starts the export and waits for it to finish. The archive is always encrypted and Skycloak deletes it 24 hours after completion, so download_url becomes null once expires_at has passed — recreate the resource to produce a fresh export.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,skycloak}
type RealmExport struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.encryptionPasswordSecretRef)",message="spec.forProvider.encryptionPasswordSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.realm) || (has(self.initProvider) && has(self.initProvider.realm))",message="spec.forProvider.realm is a required parameter"
	Spec   RealmExportSpec   `json:"spec"`
	Status RealmExportStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RealmExportList contains a list of RealmExports
type RealmExportList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RealmExport `json:"items"`
}

// Repository type metadata.
var (
	RealmExport_Kind             = "RealmExport"
	RealmExport_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RealmExport_Kind}.String()
	RealmExport_KindAPIVersion   = RealmExport_Kind + "." + CRDGroupVersion.String()
	RealmExport_GroupVersionKind = CRDGroupVersion.WithKind(RealmExport_Kind)
)

func init() {
	SchemeBuilder.Register(&RealmExport{}, &RealmExportList{})
}
