/*
Copyright 2026 Decade Engineering
*/

// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type RealmImportInitParameters struct {

	// (String) Target cluster ID. Immutable.
	// Target cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/namespaced/skycloak/v1alpha1.Cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`

	// only; never read back. Immutable.
	// Password that decrypts the artifact. Required for an encrypted archive (anything produced by `skycloak_realm_export`); omit only for a bare foreign realm JSON. Write-only; never read back. Immutable.
	PasswordSecretRef *v2.LocalSecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// (String) ID of a stored skycloak_realm_export to import from. Required when source_kind is stored. Immutable.
	// ID of a stored `skycloak_realm_export` to import from. Required when `source_kind` is `stored`. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/namespaced/skycloak/v1alpha1.RealmExport
	SourceExportID *string `json:"sourceExportId,omitempty" tf:"source_export_id,omitempty"`

	// Reference to a RealmExport in skycloak to populate sourceExportId.
	// +kubebuilder:validation:Optional
	SourceExportIDRef *v2.NamespacedReference `json:"sourceExportIdRef,omitempty" tf:"-"`

	// Selector for a RealmExport in skycloak to populate sourceExportId.
	// +kubebuilder:validation:Optional
	SourceExportIDSelector *v2.NamespacedSelector `json:"sourceExportIdSelector,omitempty" tf:"-"`

	// (String) Path to a local realm artifact to upload. Required when source_kind is upload. Immutable.
	// Path to a local realm artifact to upload. Required when `source_kind` is `upload`. Immutable.
	SourceFile *string `json:"sourceFile,omitempty" tf:"source_file,omitempty"`

	// (String) Where the artifact comes from: upload (default, uses source_file) or stored (uses source_export_id). Immutable.
	// Where the artifact comes from: `upload` (default, uses `source_file`) or `stored` (uses `source_export_id`). Immutable.
	SourceKind *string `json:"sourceKind,omitempty" tf:"source_kind,omitempty"`
}

type RealmImportObservation struct {

	// (String) Target cluster ID. Immutable.
	// Target cluster ID. Immutable.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (String) Completion timestamp (RFC 3339).
	// Completion timestamp (RFC 3339).
	CompletedAt *string `json:"completedAt,omitempty" tf:"completed_at,omitempty"`

	// (String) Creation timestamp (RFC 3339).
	// Creation timestamp (RFC 3339).
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) Realm import job ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// 100).
	// Completion percentage (0-100).
	Progress *float64 `json:"progress,omitempty" tf:"progress,omitempty"`

	// (String) Name of the imported realm, derived from the artifact.
	// Name of the imported realm, derived from the artifact.
	Realm *string `json:"realm,omitempty" tf:"realm,omitempty"`

	// (String) ID of a stored skycloak_realm_export to import from. Required when source_kind is stored. Immutable.
	// ID of a stored `skycloak_realm_export` to import from. Required when `source_kind` is `stored`. Immutable.
	SourceExportID *string `json:"sourceExportId,omitempty" tf:"source_export_id,omitempty"`

	// (String) Path to a local realm artifact to upload. Required when source_kind is upload. Immutable.
	// Path to a local realm artifact to upload. Required when `source_kind` is `upload`. Immutable.
	SourceFile *string `json:"sourceFile,omitempty" tf:"source_file,omitempty"`

	// 256 of source_file, tracked so a change to the file's bytes forces a new import even when the path is unchanged.
	// SHA-256 of `source_file`, tracked so a change to the file's bytes forces a new import even when the path is unchanged.
	SourceFileSha256 *string `json:"sourceFileSha256,omitempty" tf:"source_file_sha256,omitempty"`

	// (String) Where the artifact comes from: upload (default, uses source_file) or stored (uses source_export_id). Immutable.
	// Where the artifact comes from: `upload` (default, uses `source_file`) or `stored` (uses `source_export_id`). Immutable.
	SourceKind *string `json:"sourceKind,omitempty" tf:"source_kind,omitempty"`

	// (String) Keycloak version that produced the artifact.
	// Keycloak version that produced the artifact.
	SourceVersion *string `json:"sourceVersion,omitempty" tf:"source_version,omitempty"`

	// (String) Job status (pending, processing, completed, failed).
	// Job status (`pending`, `processing`, `completed`, `failed`).
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (String) Target cluster's Keycloak version at import time.
	// Target cluster's Keycloak version at import time.
	TargetVersion *string `json:"targetVersion,omitempty" tf:"target_version,omitempty"`
}

type RealmImportParameters struct {

	// (String) Target cluster ID. Immutable.
	// Target cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/namespaced/skycloak/v1alpha1.Cluster
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`

	// only; never read back. Immutable.
	// Password that decrypts the artifact. Required for an encrypted archive (anything produced by `skycloak_realm_export`); omit only for a bare foreign realm JSON. Write-only; never read back. Immutable.
	// +kubebuilder:validation:Optional
	PasswordSecretRef *v2.LocalSecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// (String) ID of a stored skycloak_realm_export to import from. Required when source_kind is stored. Immutable.
	// ID of a stored `skycloak_realm_export` to import from. Required when `source_kind` is `stored`. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/namespaced/skycloak/v1alpha1.RealmExport
	// +kubebuilder:validation:Optional
	SourceExportID *string `json:"sourceExportId,omitempty" tf:"source_export_id,omitempty"`

	// Reference to a RealmExport in skycloak to populate sourceExportId.
	// +kubebuilder:validation:Optional
	SourceExportIDRef *v2.NamespacedReference `json:"sourceExportIdRef,omitempty" tf:"-"`

	// Selector for a RealmExport in skycloak to populate sourceExportId.
	// +kubebuilder:validation:Optional
	SourceExportIDSelector *v2.NamespacedSelector `json:"sourceExportIdSelector,omitempty" tf:"-"`

	// (String) Path to a local realm artifact to upload. Required when source_kind is upload. Immutable.
	// Path to a local realm artifact to upload. Required when `source_kind` is `upload`. Immutable.
	// +kubebuilder:validation:Optional
	SourceFile *string `json:"sourceFile,omitempty" tf:"source_file,omitempty"`

	// (String) Where the artifact comes from: upload (default, uses source_file) or stored (uses source_export_id). Immutable.
	// Where the artifact comes from: `upload` (default, uses `source_file`) or `stored` (uses `source_export_id`). Immutable.
	// +kubebuilder:validation:Optional
	SourceKind *string `json:"sourceKind,omitempty" tf:"source_kind,omitempty"`
}

// RealmImportSpec defines the desired state of RealmImport
type RealmImportSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            RealmImportParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RealmImportInitParameters `json:"initProvider,omitempty"`
}

// RealmImportStatus defines the observed state of RealmImport.
type RealmImportStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               RealmImportObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RealmImport is the Schema for the RealmImports API. Imports a realm (configuration, users, and credentials) into a cluster. Creating the resource starts the import and waits for it to finish. The resource tracks the import job, not the resulting realm: destroying it removes the job from state and leaves the imported realm in place. Preflight validates the target Keycloak version, refuses a realm-name collision, and blocks on missing password-hash providers.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,skycloak}
type RealmImport struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              RealmImportSpec   `json:"spec"`
	Status            RealmImportStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RealmImportList contains a list of RealmImports
type RealmImportList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RealmImport `json:"items"`
}

// Repository type metadata.
var (
	RealmImport_Kind             = "RealmImport"
	RealmImport_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RealmImport_Kind}.String()
	RealmImport_KindAPIVersion   = RealmImport_Kind + "." + CRDGroupVersion.String()
	RealmImport_GroupVersionKind = CRDGroupVersion.WithKind(RealmImport_Kind)
)

func init() {
	SchemeBuilder.Register(&RealmImport{}, &RealmImportList{})
}
