/*
Copyright 2026 Decade Engineering
*/

// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type RealmRoleInitParameters struct {

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/namespaced/skycloak/v1alpha1.Cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`

	// friendly role description.
	// Human-friendly role description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Role name. Immutable (renaming recreates the role).
	// Role name. Immutable (renaming recreates the role).
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`
}

type RealmRoleObservation struct {

	// scoped role.
	// Whether this is a client-scoped role.
	ClientRole *bool `json:"clientRole,omitempty" tf:"client_role,omitempty"`

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (Boolean) Whether this role is composed from other roles.
	// Whether this role is composed from other roles.
	Composite *bool `json:"composite,omitempty" tf:"composite,omitempty"`

	// friendly role description.
	// Human-friendly role description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Composite ID cluster_id/realm_name/role_name.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Role name. Immutable (renaming recreates the role).
	// Role name. Immutable (renaming recreates the role).
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`
}

type RealmRoleParameters struct {

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/namespaced/skycloak/v1alpha1.Cluster
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`

	// friendly role description.
	// Human-friendly role description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Role name. Immutable (renaming recreates the role).
	// Role name. Immutable (renaming recreates the role).
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	// +kubebuilder:validation:Optional
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`
}

// RealmRoleSpec defines the desired state of RealmRole
type RealmRoleSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            RealmRoleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RealmRoleInitParameters `json:"initProvider,omitempty"`
}

// RealmRoleStatus defines the observed state of RealmRole.
type RealmRoleStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               RealmRoleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RealmRole is the Schema for the RealmRoles API. A realm-scoped role. Assign it to users with skycloak_realm_user_role_assignment.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,skycloak}
type RealmRole struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.realmName) || (has(self.initProvider) && has(self.initProvider.realmName))",message="spec.forProvider.realmName is a required parameter"
	Spec   RealmRoleSpec   `json:"spec"`
	Status RealmRoleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RealmRoleList contains a list of RealmRoles
type RealmRoleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RealmRole `json:"items"`
}

// Repository type metadata.
var (
	RealmRole_Kind             = "RealmRole"
	RealmRole_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RealmRole_Kind}.String()
	RealmRole_KindAPIVersion   = RealmRole_Kind + "." + CRDGroupVersion.String()
	RealmRole_GroupVersionKind = CRDGroupVersion.WithKind(RealmRole_Kind)
)

func init() {
	SchemeBuilder.Register(&RealmRole{}, &RealmRoleList{})
}
