/*
Copyright 2026 Decade Engineering
*/

// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type RealmInitParameters struct {

	// (String) ID of the cluster the realm belongs to. Immutable.
	// ID of the cluster the realm belongs to. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/namespaced/skycloak/v1alpha1.Cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`

	// readable realm display name.
	// Human-readable realm display name.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Boolean) Allow duplicate emails across users. Defaults to false.
	// Allow duplicate emails across users. Defaults to `false`.
	DuplicateEmailsAllowed *bool `json:"duplicateEmailsAllowed,omitempty" tf:"duplicate_emails_allowed,omitempty"`

	// (Boolean) Whether the realm is enabled. Defaults to true.
	// Whether the realm is enabled. Defaults to `true`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Boolean) Allow login with email. Defaults to false.
	// Allow login with email. Defaults to `false`.
	LoginWithEmailAllowed *bool `json:"loginWithEmailAllowed,omitempty" tf:"login_with_email_allowed,omitempty"`

	// (String) Realm name (the Keycloak realm key). Immutable.
	// Realm name (the Keycloak realm key). Immutable.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// registration. Defaults to false.
	// Allow self-registration. Defaults to `false`.
	RegistrationAllowed *bool `json:"registrationAllowed,omitempty" tf:"registration_allowed,omitempty"`

	// (Boolean) Use email as username on registration. Defaults to false.
	// Use email as username on registration. Defaults to `false`.
	RegistrationEmailAsUsername *bool `json:"registrationEmailAsUsername,omitempty" tf:"registration_email_as_username,omitempty"`

	// (String) SSL requirement: external, all, or none. Defaults to external.
	// SSL requirement: `external`, `all`, or `none`. Defaults to `external`.
	SSLRequired *string `json:"sslRequired,omitempty" tf:"ssl_required,omitempty"`
}

type RealmObservation struct {

	// (String) ID of the cluster the realm belongs to. Immutable.
	// ID of the cluster the realm belongs to. Immutable.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (String) Creation timestamp.
	// Creation timestamp.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// readable realm display name.
	// Human-readable realm display name.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Boolean) Allow duplicate emails across users. Defaults to false.
	// Allow duplicate emails across users. Defaults to `false`.
	DuplicateEmailsAllowed *bool `json:"duplicateEmailsAllowed,omitempty" tf:"duplicate_emails_allowed,omitempty"`

	// (Boolean) Whether the realm is enabled. Defaults to true.
	// Whether the realm is enabled. Defaults to `true`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Composite ID cluster_id/name.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Allow login with email. Defaults to false.
	// Allow login with email. Defaults to `false`.
	LoginWithEmailAllowed *bool `json:"loginWithEmailAllowed,omitempty" tf:"login_with_email_allowed,omitempty"`

	// (String) Realm name (the Keycloak realm key). Immutable.
	// Realm name (the Keycloak realm key). Immutable.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// registration. Defaults to false.
	// Allow self-registration. Defaults to `false`.
	RegistrationAllowed *bool `json:"registrationAllowed,omitempty" tf:"registration_allowed,omitempty"`

	// (Boolean) Use email as username on registration. Defaults to false.
	// Use email as username on registration. Defaults to `false`.
	RegistrationEmailAsUsername *bool `json:"registrationEmailAsUsername,omitempty" tf:"registration_email_as_username,omitempty"`

	// (String) SSL requirement: external, all, or none. Defaults to external.
	// SSL requirement: `external`, `all`, or `none`. Defaults to `external`.
	SSLRequired *string `json:"sslRequired,omitempty" tf:"ssl_required,omitempty"`
}

type RealmParameters struct {

	// (String) ID of the cluster the realm belongs to. Immutable.
	// ID of the cluster the realm belongs to. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/namespaced/skycloak/v1alpha1.Cluster
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`

	// readable realm display name.
	// Human-readable realm display name.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Boolean) Allow duplicate emails across users. Defaults to false.
	// Allow duplicate emails across users. Defaults to `false`.
	// +kubebuilder:validation:Optional
	DuplicateEmailsAllowed *bool `json:"duplicateEmailsAllowed,omitempty" tf:"duplicate_emails_allowed,omitempty"`

	// (Boolean) Whether the realm is enabled. Defaults to true.
	// Whether the realm is enabled. Defaults to `true`.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Boolean) Allow login with email. Defaults to false.
	// Allow login with email. Defaults to `false`.
	// +kubebuilder:validation:Optional
	LoginWithEmailAllowed *bool `json:"loginWithEmailAllowed,omitempty" tf:"login_with_email_allowed,omitempty"`

	// (String) Realm name (the Keycloak realm key). Immutable.
	// Realm name (the Keycloak realm key). Immutable.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// registration. Defaults to false.
	// Allow self-registration. Defaults to `false`.
	// +kubebuilder:validation:Optional
	RegistrationAllowed *bool `json:"registrationAllowed,omitempty" tf:"registration_allowed,omitempty"`

	// (Boolean) Use email as username on registration. Defaults to false.
	// Use email as username on registration. Defaults to `false`.
	// +kubebuilder:validation:Optional
	RegistrationEmailAsUsername *bool `json:"registrationEmailAsUsername,omitempty" tf:"registration_email_as_username,omitempty"`

	// (String) SSL requirement: external, all, or none. Defaults to external.
	// SSL requirement: `external`, `all`, or `none`. Defaults to `external`.
	// +kubebuilder:validation:Optional
	SSLRequired *string `json:"sslRequired,omitempty" tf:"ssl_required,omitempty"`
}

// RealmSpec defines the desired state of Realm
type RealmSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            RealmParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RealmInitParameters `json:"initProvider,omitempty"`
}

// RealmStatus defines the observed state of Realm.
type RealmStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               RealmObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Realm is the Schema for the Realms API. A Keycloak realm within a Skycloak cluster.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,skycloak}
type Realm struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   RealmSpec   `json:"spec"`
	Status RealmStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RealmList contains a list of Realms
type RealmList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Realm `json:"items"`
}

// Repository type metadata.
var (
	Realm_Kind             = "Realm"
	Realm_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Realm_Kind}.String()
	Realm_KindAPIVersion   = Realm_Kind + "." + CRDGroupVersion.String()
	Realm_GroupVersionKind = CRDGroupVersion.WithKind(Realm_Kind)
)

func init() {
	SchemeBuilder.Register(&Realm{}, &RealmList{})
}
