/*
Copyright 2026 Decade Engineering
*/

// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type BatchInitParameters struct {

	// (Number) Flush after this many events. Defaults to 1000.
	// Flush after this many events. Defaults to `1000`.
	MaxEvents *float64 `json:"maxEvents,omitempty" tf:"max_events,omitempty"`

	// (Number) Flush at least this often. Defaults to 60.
	// Flush at least this often. Defaults to `60`.
	MaxIntervalSeconds *float64 `json:"maxIntervalSeconds,omitempty" tf:"max_interval_seconds,omitempty"`
}

type BatchObservation struct {

	// (Number) Flush after this many events. Defaults to 1000.
	// Flush after this many events. Defaults to `1000`.
	MaxEvents *float64 `json:"maxEvents,omitempty" tf:"max_events,omitempty"`

	// (Number) Flush at least this often. Defaults to 60.
	// Flush at least this often. Defaults to `60`.
	MaxIntervalSeconds *float64 `json:"maxIntervalSeconds,omitempty" tf:"max_interval_seconds,omitempty"`
}

type BatchParameters struct {

	// (Number) Flush after this many events. Defaults to 1000.
	// Flush after this many events. Defaults to `1000`.
	// +kubebuilder:validation:Optional
	MaxEvents *float64 `json:"maxEvents,omitempty" tf:"max_events,omitempty"`

	// (Number) Flush at least this often. Defaults to 60.
	// Flush at least this often. Defaults to `60`.
	// +kubebuilder:validation:Optional
	MaxIntervalSeconds *float64 `json:"maxIntervalSeconds,omitempty" tf:"max_interval_seconds,omitempty"`
}

type HTTPInitParameters struct {

	// (String) basic, bearer, or none.
	// `basic`, `bearer`, or `none`.
	AuthType *string `json:"authType,omitempty" tf:"auth_type,omitempty"`

	// only.
	// Bearer token (when `auth_type` is `bearer`). Write-only.
	BearerTokenSecretRef *v2.LocalSecretKeySelector `json:"bearerTokenSecretRef,omitempty" tf:"-"`

	Headers map[string]*string `json:"headersSecretRef,omitempty" tf:"-"`

	// only.
	// Password (when `auth_type` is `basic`). Write-only.
	PasswordSecretRef *v2.LocalSecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// (String) Collector endpoint URL.
	// Collector endpoint URL.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// (String) Username (when auth_type is basic).
	// Username (when `auth_type` is `basic`).
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type HTTPObservation struct {

	// (String) basic, bearer, or none.
	// `basic`, `bearer`, or `none`.
	AuthType *string `json:"authType,omitempty" tf:"auth_type,omitempty"`

	// (Boolean) Whether auth credentials are stored.
	// Whether auth credentials are stored.
	HasAuthCredentials *bool `json:"hasAuthCredentials,omitempty" tf:"has_auth_credentials,omitempty"`

	// (String) Collector endpoint URL.
	// Collector endpoint URL.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// (String) Username (when auth_type is basic).
	// Username (when `auth_type` is `basic`).
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type HTTPParameters struct {

	// (String) basic, bearer, or none.
	// `basic`, `bearer`, or `none`.
	// +kubebuilder:validation:Optional
	AuthType *string `json:"authType" tf:"auth_type,omitempty"`

	// only.
	// Bearer token (when `auth_type` is `bearer`). Write-only.
	// +kubebuilder:validation:Optional
	BearerTokenSecretRef *v2.LocalSecretKeySelector `json:"bearerTokenSecretRef,omitempty" tf:"-"`

	// only; reads return header names only.
	// Extra HTTP headers. Values are write-only; reads return header names only.
	// +kubebuilder:validation:Optional
	HeadersSecretRef *v2.LocalSecretReference `json:"headersSecretRef,omitempty" tf:"-"`

	// only.
	// Password (when `auth_type` is `basic`). Write-only.
	// +kubebuilder:validation:Optional
	PasswordSecretRef *v2.LocalSecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// (String) Collector endpoint URL.
	// Collector endpoint URL.
	// +kubebuilder:validation:Optional
	URL *string `json:"url" tf:"url,omitempty"`

	// (String) Username (when auth_type is basic).
	// Username (when `auth_type` is `basic`).
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type S3InitParameters struct {

	// only.
	// Access key ID (when `auth_type` is `access_key`). Write-only.
	AccessKeyIDSecretRef *v2.LocalSecretKeySelector `json:"accessKeyIdSecretRef,omitempty" tf:"-"`

	// (String) basic, bearer, or none.
	// `access_key`, `assume_role`, `iam_role`, or `irsa`.
	AuthType *string `json:"authType,omitempty" tf:"auth_type,omitempty"`

	// (String) Bucket name.
	// Bucket name.
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// (String) External ID for role assumption.
	// External ID for role assumption.
	ExternalID *string `json:"externalId,omitempty" tf:"external_id,omitempty"`

	// (String) Object key prefix.
	// Object key prefix.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`

	// (String) Bucket region.
	// Bucket region.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) Role ARN (when auth_type is assume_role).
	// Role ARN (when `auth_type` is `assume_role`).
	RoleArn *string `json:"roleArn,omitempty" tf:"role_arn,omitempty"`

	// only.
	// Secret access key (when `auth_type` is `access_key`). Write-only.
	SecretAccessKeySecretRef *v2.LocalSecretKeySelector `json:"secretAccessKeySecretRef,omitempty" tf:"-"`
}

type S3Observation struct {

	// (String) basic, bearer, or none.
	// `access_key`, `assume_role`, `iam_role`, or `irsa`.
	AuthType *string `json:"authType,omitempty" tf:"auth_type,omitempty"`

	// (String) Bucket name.
	// Bucket name.
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// (String) External ID for role assumption.
	// External ID for role assumption.
	ExternalID *string `json:"externalId,omitempty" tf:"external_id,omitempty"`

	// (Boolean) Whether a secret access key is stored.
	// Whether a secret access key is stored.
	HasAccessKeySecret *bool `json:"hasAccessKeySecret,omitempty" tf:"has_access_key_secret,omitempty"`

	// (String) Object key prefix.
	// Object key prefix.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`

	// (String) Bucket region.
	// Bucket region.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) Role ARN (when auth_type is assume_role).
	// Role ARN (when `auth_type` is `assume_role`).
	RoleArn *string `json:"roleArn,omitempty" tf:"role_arn,omitempty"`
}

type S3Parameters struct {

	// only.
	// Access key ID (when `auth_type` is `access_key`). Write-only.
	// +kubebuilder:validation:Optional
	AccessKeyIDSecretRef *v2.LocalSecretKeySelector `json:"accessKeyIdSecretRef,omitempty" tf:"-"`

	// (String) basic, bearer, or none.
	// `access_key`, `assume_role`, `iam_role`, or `irsa`.
	// +kubebuilder:validation:Optional
	AuthType *string `json:"authType" tf:"auth_type,omitempty"`

	// (String) Bucket name.
	// Bucket name.
	// +kubebuilder:validation:Optional
	Bucket *string `json:"bucket" tf:"bucket,omitempty"`

	// (String) External ID for role assumption.
	// External ID for role assumption.
	// +kubebuilder:validation:Optional
	ExternalID *string `json:"externalId,omitempty" tf:"external_id,omitempty"`

	// (String) Object key prefix.
	// Object key prefix.
	// +kubebuilder:validation:Optional
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`

	// (String) Bucket region.
	// Bucket region.
	// +kubebuilder:validation:Optional
	Region *string `json:"region" tf:"region,omitempty"`

	// (String) Role ARN (when auth_type is assume_role).
	// Role ARN (when `auth_type` is `assume_role`).
	// +kubebuilder:validation:Optional
	RoleArn *string `json:"roleArn,omitempty" tf:"role_arn,omitempty"`

	// only.
	// Secret access key (when `auth_type` is `access_key`). Write-only.
	// +kubebuilder:validation:Optional
	SecretAccessKeySecretRef *v2.LocalSecretKeySelector `json:"secretAccessKeySecretRef,omitempty" tf:"-"`
}

type SIEMDestinationInitParameters struct {

	// (Attributes) Batching tuning. Defaults to the API contract values (1000 events, 60 seconds) so an omitted block plans exactly what the server applies. (see below for nested schema)
	Batch *BatchInitParameters `json:"batch,omitempty" tf:"batch,omitempty"`

	// (Boolean) Whether forwarding is active. Defaults to true.
	// Whether forwarding is active. Defaults to `true`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Attributes) HTTP destination config (when type is http). (see below for nested schema)
	HTTP *HTTPInitParameters `json:"http,omitempty" tf:"http,omitempty"`

	// (String) Destination name.
	// Destination name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) S3 destination config (when type is s3). (see below for nested schema)
	S3 *S3InitParameters `json:"s3,omitempty" tf:"s3,omitempty"`

	// (Attributes) Which workspace data stream is forwarded. (see below for nested schema)
	Source *SourceInitParameters `json:"source,omitempty" tf:"source,omitempty"`

	// (Attributes) Syslog destination config (when type is syslog). (see below for nested schema)
	Syslog *SyslogInitParameters `json:"syslog,omitempty" tf:"syslog,omitempty"`

	// (String) Destination type: syslog, s3, or http. Immutable.
	// Destination type: `syslog`, `s3`, or `http`. Immutable.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type SIEMDestinationObservation struct {

	// (Attributes) Batching tuning. Defaults to the API contract values (1000 events, 60 seconds) so an omitted block plans exactly what the server applies. (see below for nested schema)
	Batch *BatchObservation `json:"batch,omitempty" tf:"batch,omitempty"`

	// (String)
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (Boolean) Whether forwarding is active. Defaults to true.
	// Whether forwarding is active. Defaults to `true`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Number) Consecutive delivery failures.
	// Consecutive delivery failures.
	FailureCount *float64 `json:"failureCount,omitempty" tf:"failure_count,omitempty"`

	// (Attributes) HTTP destination config (when type is http). (see below for nested schema)
	HTTP *HTTPObservation `json:"http,omitempty" tf:"http,omitempty"`

	// (String) healthy, degraded, or failed.
	// `healthy`, `degraded`, or `failed`.
	HealthStatus *string `json:"healthStatus,omitempty" tf:"health_status,omitempty"`

	// (String) Destination ID (UUID).
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Most recent delivery error.
	// Most recent delivery error.
	LastError *string `json:"lastError,omitempty" tf:"last_error,omitempty"`

	// (String) Last successful delivery.
	// Last successful delivery.
	LastSentAt *string `json:"lastSentAt,omitempty" tf:"last_sent_at,omitempty"`

	// (String) Destination name.
	// Destination name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) S3 destination config (when type is s3). (see below for nested schema)
	S3 *S3Observation `json:"s3,omitempty" tf:"s3,omitempty"`

	// (Attributes) Which workspace data stream is forwarded. (see below for nested schema)
	Source *SourceObservation `json:"source,omitempty" tf:"source,omitempty"`

	// (Attributes) Syslog destination config (when type is syslog). (see below for nested schema)
	Syslog *SyslogObservation `json:"syslog,omitempty" tf:"syslog,omitempty"`

	// (Number)
	TotalBytesSent *float64 `json:"totalBytesSent,omitempty" tf:"total_bytes_sent,omitempty"`

	// (Number)
	TotalEventsSent *float64 `json:"totalEventsSent,omitempty" tf:"total_events_sent,omitempty"`

	// (Number)
	TotalLogsSent *float64 `json:"totalLogsSent,omitempty" tf:"total_logs_sent,omitempty"`

	// (String) Destination type: syslog, s3, or http. Immutable.
	// Destination type: `syslog`, `s3`, or `http`. Immutable.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String)
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type SIEMDestinationParameters struct {

	// (Attributes) Batching tuning. Defaults to the API contract values (1000 events, 60 seconds) so an omitted block plans exactly what the server applies. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Batch *BatchParameters `json:"batch,omitempty" tf:"batch,omitempty"`

	// (Boolean) Whether forwarding is active. Defaults to true.
	// Whether forwarding is active. Defaults to `true`.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Attributes) HTTP destination config (when type is http). (see below for nested schema)
	// +kubebuilder:validation:Optional
	HTTP *HTTPParameters `json:"http,omitempty" tf:"http,omitempty"`

	// (String) Destination name.
	// Destination name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) S3 destination config (when type is s3). (see below for nested schema)
	// +kubebuilder:validation:Optional
	S3 *S3Parameters `json:"s3,omitempty" tf:"s3,omitempty"`

	// (Attributes) Which workspace data stream is forwarded. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Source *SourceParameters `json:"source,omitempty" tf:"source,omitempty"`

	// (Attributes) Syslog destination config (when type is syslog). (see below for nested schema)
	// +kubebuilder:validation:Optional
	Syslog *SyslogParameters `json:"syslog,omitempty" tf:"syslog,omitempty"`

	// (String) Destination type: syslog, s3, or http. Immutable.
	// Destination type: `syslog`, `s3`, or `http`. Immutable.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type SourceInitParameters struct {

	// (List of String) Cluster IDs to include. Omit for all clusters.
	// Cluster IDs to include. Omit for all clusters.
	ClusterIds []*string `json:"clusterIds,omitempty" tf:"cluster_ids,omitempty"`

	// (List of String) Keycloak event type codes. Required when type is keycloak_events.
	// Keycloak event type codes. Required when `type` is `keycloak_events`.
	KeycloakEventTypes []*string `json:"keycloakEventTypes,omitempty" tf:"keycloak_event_types,omitempty"`

	// (List of String) Realm names to include. Omit for all realms.
	// Realm names to include. Omit for all realms.
	Realms []*string `json:"realms,omitempty" tf:"realms,omitempty"`

	// (String) Destination type: syslog, s3, or http. Immutable.
	// Stream: `application_logs`, `keycloak_events`, `security_logs`, or `skycloak_audit`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type SourceObservation struct {

	// (List of String) Cluster IDs to include. Omit for all clusters.
	// Cluster IDs to include. Omit for all clusters.
	ClusterIds []*string `json:"clusterIds,omitempty" tf:"cluster_ids,omitempty"`

	// (List of String) Keycloak event type codes. Required when type is keycloak_events.
	// Keycloak event type codes. Required when `type` is `keycloak_events`.
	KeycloakEventTypes []*string `json:"keycloakEventTypes,omitempty" tf:"keycloak_event_types,omitempty"`

	// (List of String) Realm names to include. Omit for all realms.
	// Realm names to include. Omit for all realms.
	Realms []*string `json:"realms,omitempty" tf:"realms,omitempty"`

	// (String) Destination type: syslog, s3, or http. Immutable.
	// Stream: `application_logs`, `keycloak_events`, `security_logs`, or `skycloak_audit`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type SourceParameters struct {

	// (List of String) Cluster IDs to include. Omit for all clusters.
	// Cluster IDs to include. Omit for all clusters.
	// +kubebuilder:validation:Optional
	ClusterIds []*string `json:"clusterIds,omitempty" tf:"cluster_ids,omitempty"`

	// (List of String) Keycloak event type codes. Required when type is keycloak_events.
	// Keycloak event type codes. Required when `type` is `keycloak_events`.
	// +kubebuilder:validation:Optional
	KeycloakEventTypes []*string `json:"keycloakEventTypes,omitempty" tf:"keycloak_event_types,omitempty"`

	// (List of String) Realm names to include. Omit for all realms.
	// Realm names to include. Omit for all realms.
	// +kubebuilder:validation:Optional
	Realms []*string `json:"realms,omitempty" tf:"realms,omitempty"`

	// (String) Destination type: syslog, s3, or http. Immutable.
	// Stream: `application_logs`, `keycloak_events`, `security_logs`, or `skycloak_audit`.
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type SyslogInitParameters struct {

	// (String) rfc5424, cef, leef, or json.
	// `rfc5424`, `cef`, `leef`, or `json`.
	Format *string `json:"format,omitempty" tf:"format,omitempty"`

	// (String) Syslog server hostname or IP.
	// Syslog server hostname or IP.
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// (Number) Syslog server port.
	// Syslog server port.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// (String) tcp, tls, or udp.
	// `tcp`, `tls`, or `udp`.
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`
}

type SyslogObservation struct {

	// (String) rfc5424, cef, leef, or json.
	// `rfc5424`, `cef`, `leef`, or `json`.
	Format *string `json:"format,omitempty" tf:"format,omitempty"`

	// (String) Syslog server hostname or IP.
	// Syslog server hostname or IP.
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// (Number) Syslog server port.
	// Syslog server port.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// (String) tcp, tls, or udp.
	// `tcp`, `tls`, or `udp`.
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`
}

type SyslogParameters struct {

	// (String) rfc5424, cef, leef, or json.
	// `rfc5424`, `cef`, `leef`, or `json`.
	// +kubebuilder:validation:Optional
	Format *string `json:"format" tf:"format,omitempty"`

	// (String) Syslog server hostname or IP.
	// Syslog server hostname or IP.
	// +kubebuilder:validation:Optional
	Host *string `json:"host" tf:"host,omitempty"`

	// (Number) Syslog server port.
	// Syslog server port.
	// +kubebuilder:validation:Optional
	Port *float64 `json:"port" tf:"port,omitempty"`

	// (String) tcp, tls, or udp.
	// `tcp`, `tls`, or `udp`.
	// +kubebuilder:validation:Optional
	Protocol *string `json:"protocol" tf:"protocol,omitempty"`
}

// SIEMDestinationSpec defines the desired state of SIEMDestination
type SIEMDestinationSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            SIEMDestinationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SIEMDestinationInitParameters `json:"initProvider,omitempty"`
}

// SIEMDestinationStatus defines the observed state of SIEMDestination.
type SIEMDestinationStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               SIEMDestinationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SIEMDestination is the Schema for the SIEMDestinations API. A SIEM forwarding destination for the workspace (syslog, S3, or HTTP). SIEM forwarding is plan-gated; the API rejects the calls on plans without it.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,skycloak}
type SIEMDestination struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.source) || (has(self.initProvider) && has(self.initProvider.source))",message="spec.forProvider.source is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   SIEMDestinationSpec   `json:"spec"`
	Status SIEMDestinationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SIEMDestinationList contains a list of SIEMDestinations
type SIEMDestinationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SIEMDestination `json:"items"`
}

// Repository type metadata.
var (
	SIEMDestination_Kind             = "SIEMDestination"
	SIEMDestination_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SIEMDestination_Kind}.String()
	SIEMDestination_KindAPIVersion   = SIEMDestination_Kind + "." + CRDGroupVersion.String()
	SIEMDestination_GroupVersionKind = CRDGroupVersion.WithKind(SIEMDestination_Kind)
)

func init() {
	SchemeBuilder.Register(&SIEMDestination{}, &SIEMDestinationList{})
}
