/*
Copyright 2026 Decade Engineering
*/

// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ThemeAssignmentInitParameters struct {

	// in default.
	// Custom theme ID to activate for the account console. Omit to use Keycloak's built-in default.
	Account *string `json:"account,omitempty" tf:"account,omitempty"`

	// in default.
	// Custom theme ID to activate for the admin console. Omit to use Keycloak's built-in default.
	Admin *string `json:"admin,omitempty" tf:"admin,omitempty"`

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/namespaced/skycloak/v1alpha1.Cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`

	// in default.
	// Custom theme ID to activate for the email templates. Omit to use Keycloak's built-in default.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// in default.
	// Custom theme ID to activate for the login page. Omit to use Keycloak's built-in default.
	Login *string `json:"login,omitempty" tf:"login,omitempty"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`
}

type ThemeAssignmentObservation struct {

	// in default.
	// Custom theme ID to activate for the account console. Omit to use Keycloak's built-in default.
	Account *string `json:"account,omitempty" tf:"account,omitempty"`

	// in default.
	// Custom theme ID to activate for the admin console. Omit to use Keycloak's built-in default.
	Admin *string `json:"admin,omitempty" tf:"admin,omitempty"`

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// in default.
	// Custom theme ID to activate for the email templates. Omit to use Keycloak's built-in default.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// (String) Composite ID cluster_id/realm_name/theme_assignment.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// in default.
	// Custom theme ID to activate for the login page. Omit to use Keycloak's built-in default.
	Login *string `json:"login,omitempty" tf:"login,omitempty"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`
}

type ThemeAssignmentParameters struct {

	// in default.
	// Custom theme ID to activate for the account console. Omit to use Keycloak's built-in default.
	// +kubebuilder:validation:Optional
	Account *string `json:"account,omitempty" tf:"account,omitempty"`

	// in default.
	// Custom theme ID to activate for the admin console. Omit to use Keycloak's built-in default.
	// +kubebuilder:validation:Optional
	Admin *string `json:"admin,omitempty" tf:"admin,omitempty"`

	// (String) Cluster ID. Immutable.
	// Cluster ID. Immutable.
	// +crossplane:generate:reference:type=github.com/decade-eng/provider-skycloak/apis/namespaced/skycloak/v1alpha1.Cluster
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in skycloak to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`

	// in default.
	// Custom theme ID to activate for the email templates. Omit to use Keycloak's built-in default.
	// +kubebuilder:validation:Optional
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// in default.
	// Custom theme ID to activate for the login page. Omit to use Keycloak's built-in default.
	// +kubebuilder:validation:Optional
	Login *string `json:"login,omitempty" tf:"login,omitempty"`

	// (String) Realm name. Immutable.
	// Realm name. Immutable.
	// +kubebuilder:validation:Optional
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`
}

// ThemeAssignmentSpec defines the desired state of ThemeAssignment
type ThemeAssignmentSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ThemeAssignmentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ThemeAssignmentInitParameters `json:"initProvider,omitempty"`
}

// ThemeAssignmentStatus defines the observed state of ThemeAssignment.
type ThemeAssignmentStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ThemeAssignmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ThemeAssignment is the Schema for the ThemeAssignments API. Realm-level custom theme assignment per Keycloak theme type. A singleton per realm; managing this resource asserts the full assignment.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,skycloak}
type ThemeAssignment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.realmName) || (has(self.initProvider) && has(self.initProvider.realmName))",message="spec.forProvider.realmName is a required parameter"
	Spec   ThemeAssignmentSpec   `json:"spec"`
	Status ThemeAssignmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ThemeAssignmentList contains a list of ThemeAssignments
type ThemeAssignmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ThemeAssignment `json:"items"`
}

// Repository type metadata.
var (
	ThemeAssignment_Kind             = "ThemeAssignment"
	ThemeAssignment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ThemeAssignment_Kind}.String()
	ThemeAssignment_KindAPIVersion   = ThemeAssignment_Kind + "." + CRDGroupVersion.String()
	ThemeAssignment_GroupVersionKind = CRDGroupVersion.WithKind(ThemeAssignment_Kind)
)

func init() {
	SchemeBuilder.Register(&ThemeAssignment{}, &ThemeAssignmentList{})
}
