/*
Copyright 2026 Decade Engineering
*/

// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type WebhookSubscriptionInitParameters struct {

	// only; omit to retain the stored value.
	// Authorization header value sent with each delivery. Write-only; omit to retain the stored value.
	AuthorizationHeaderSecretRef *v2.LocalSecretKeySelector `json:"authorizationHeaderSecretRef,omitempty" tf:"-"`

	// (String) Scope deliveries to one cluster. Omit for all clusters.
	// Scope deliveries to one cluster. Omit for all clusters.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (Boolean) Whether deliveries are active. Defaults to true.
	// Whether deliveries are active. Defaults to `true`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (List of String) Event types to deliver. See the skycloak_webhook_event_types data source for the catalog.
	// Event types to deliver. See the `skycloak_webhook_event_types` data source for the catalog.
	EventTypes []*string `json:"eventTypes,omitempty" tf:"event_types,omitempty"`

	// (String) Subscription name.
	// Subscription name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Scope deliveries to one Keycloak realm ID (UUID).
	// Scope deliveries to one Keycloak realm ID (UUID).
	RealmID *string `json:"realmId,omitempty" tf:"realm_id,omitempty"`

	// only; never read back.
	// HMAC secret used to sign deliveries, 32 to 512 characters. Write-only; never read back.
	SigningSecretSecretRef v2.LocalSecretKeySelector `json:"signingSecretSecretRef" tf:"-"`

	// (String) Event source: keycloak or platform.
	// Event source: `keycloak` or `platform`.
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// (String) HTTPS endpoint receiving deliveries.
	// HTTPS endpoint receiving deliveries.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type WebhookSubscriptionObservation struct {

	// (String) Scope deliveries to one cluster. Omit for all clusters.
	// Scope deliveries to one cluster. Omit for all clusters.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (String)
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (Boolean) Whether deliveries are active. Defaults to true.
	// Whether deliveries are active. Defaults to `true`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (List of String) Event types to deliver. See the skycloak_webhook_event_types data source for the catalog.
	// Event types to deliver. See the `skycloak_webhook_event_types` data source for the catalog.
	EventTypes []*string `json:"eventTypes,omitempty" tf:"event_types,omitempty"`

	// (Boolean) Whether an authorization header is stored.
	// Whether an authorization header is stored.
	HasAuthorizationHeader *bool `json:"hasAuthorizationHeader,omitempty" tf:"has_authorization_header,omitempty"`

	// (Boolean) Whether a signing secret is stored.
	// Whether a signing secret is stored.
	HasSigningSecret *bool `json:"hasSigningSecret,omitempty" tf:"has_signing_secret,omitempty"`

	// (String) Subscription ID (UUID).
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Subscription name.
	// Subscription name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Scope deliveries to one Keycloak realm ID (UUID).
	// Scope deliveries to one Keycloak realm ID (UUID).
	RealmID *string `json:"realmId,omitempty" tf:"realm_id,omitempty"`

	// (String) Event source: keycloak or platform.
	// Event source: `keycloak` or `platform`.
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// (String) HTTPS endpoint receiving deliveries.
	// HTTPS endpoint receiving deliveries.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// (String)
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type WebhookSubscriptionParameters struct {

	// only; omit to retain the stored value.
	// Authorization header value sent with each delivery. Write-only; omit to retain the stored value.
	// +kubebuilder:validation:Optional
	AuthorizationHeaderSecretRef *v2.LocalSecretKeySelector `json:"authorizationHeaderSecretRef,omitempty" tf:"-"`

	// (String) Scope deliveries to one cluster. Omit for all clusters.
	// Scope deliveries to one cluster. Omit for all clusters.
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (Boolean) Whether deliveries are active. Defaults to true.
	// Whether deliveries are active. Defaults to `true`.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (List of String) Event types to deliver. See the skycloak_webhook_event_types data source for the catalog.
	// Event types to deliver. See the `skycloak_webhook_event_types` data source for the catalog.
	// +kubebuilder:validation:Optional
	EventTypes []*string `json:"eventTypes,omitempty" tf:"event_types,omitempty"`

	// (String) Subscription name.
	// Subscription name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Scope deliveries to one Keycloak realm ID (UUID).
	// Scope deliveries to one Keycloak realm ID (UUID).
	// +kubebuilder:validation:Optional
	RealmID *string `json:"realmId,omitempty" tf:"realm_id,omitempty"`

	// only; never read back.
	// HMAC secret used to sign deliveries, 32 to 512 characters. Write-only; never read back.
	// +kubebuilder:validation:Optional
	SigningSecretSecretRef v2.LocalSecretKeySelector `json:"signingSecretSecretRef" tf:"-"`

	// (String) Event source: keycloak or platform.
	// Event source: `keycloak` or `platform`.
	// +kubebuilder:validation:Optional
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// (String) HTTPS endpoint receiving deliveries.
	// HTTPS endpoint receiving deliveries.
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

// WebhookSubscriptionSpec defines the desired state of WebhookSubscription
type WebhookSubscriptionSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            WebhookSubscriptionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider WebhookSubscriptionInitParameters `json:"initProvider,omitempty"`
}

// WebhookSubscriptionStatus defines the observed state of WebhookSubscription.
type WebhookSubscriptionStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               WebhookSubscriptionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// WebhookSubscription is the Schema for the WebhookSubscriptions API. A webhook subscription delivering workspace events to an HTTPS endpoint. signing_secret and authorization_header are write-only: the API never returns them and reads report has_* booleans instead.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,skycloak}
type WebhookSubscription struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.eventTypes) || (has(self.initProvider) && has(self.initProvider.eventTypes))",message="spec.forProvider.eventTypes is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.signingSecretSecretRef)",message="spec.forProvider.signingSecretSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.source) || (has(self.initProvider) && has(self.initProvider.source))",message="spec.forProvider.source is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.url) || (has(self.initProvider) && has(self.initProvider.url))",message="spec.forProvider.url is a required parameter"
	Spec   WebhookSubscriptionSpec   `json:"spec"`
	Status WebhookSubscriptionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// WebhookSubscriptionList contains a list of WebhookSubscriptions
type WebhookSubscriptionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []WebhookSubscription `json:"items"`
}

// Repository type metadata.
var (
	WebhookSubscription_Kind             = "WebhookSubscription"
	WebhookSubscription_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: WebhookSubscription_Kind}.String()
	WebhookSubscription_KindAPIVersion   = WebhookSubscription_Kind + "." + CRDGroupVersion.String()
	WebhookSubscription_GroupVersionKind = CRDGroupVersion.WithKind(WebhookSubscription_Kind)
)

func init() {
	SchemeBuilder.Register(&WebhookSubscription{}, &WebhookSubscriptionList{})
}
