apiVersion: skycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: skycloak/v1alpha1/realm
  labels:
    testing.upbound.io/example-name: app
  name: app
spec:
  forProvider:
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: production
    displayName: Application Realm
    enabled: true
    loginWithEmailAllowed: true
    name: app

---

apiVersion: skycloak.crossplane.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: /v1alpha1/realm
  labels:
    testing.upbound.io/example-name: production
  name: production
spec:
  forProvider:
    location: eu
    name: production
    size: small
    type: keycloak
    version: "26.1"
